# -*- coding: utf-8 -*-
"""SeniorProject499.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MK2imPPqFCh4u5qFrNzZ26Qt8MiILYy
"""

# connecting to the drive

from google.colab import drive
drive.mount('/content/drive')

"""# Preprocessing Structured Data - Selena

"""

# adding path to CSVs

import csv
import pandas as pd
import numpy as np
from datetime import timedelta
import os

!ls '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/DEMO CSV Files'

# create vectors to store hadm-id's we want to use for training

def remove_duplicates(arr):
    """Remove duplicate values from an array while preserving order."""
    seen = set()
    unique = []
    for x in arr:
        if x not in seen:
            unique.append(x)
            seen.add(x)
    return unique


training_id = [142345,105331,165520,199207,177759,103770,199395,132349,140372,157235,110244,189483,111115,
               124073,126949,145203,174739,188574,167957,187023,157466,193924,182839,175237,172082];
# remove duplicates just in case
training_id = remove_duplicates(training_id)
print(training_id)

# HELPER FUNCTIONS
# ---------------------------

def load_filtered_csv(filename, usecols=None, header=1):
    """Load CSV, keep only rows with hadm_id in training_id."""
    path = f"{datapath}/{filename}"

    dtype_overrides = {
        'subject_id': 'string',
        'hadm_id': 'string',
        'icustay_id': 'string',
        'itemid': 'string',
        'row_id': 'string',
        'dob': 'string'
    }

    df = pd.read_csv(path, usecols=usecols, header=1, dtype=dtype_overrides)
    df.columns = df.columns.str.strip().str.lower()
    if 'hadm_id' in df.columns:
        df = df[df['hadm_id'].isin([str(x) for x in training_id])]
    return df


def aggregate_in_bins(df, time_col, value_cols, ref_time_col='REF_TIME'):
    """Bin events into N_HOURS windows relative to ref_time_col."""
    results = []

    for hadm, sub in df.groupby('hadm_id'):
        ref_time = sub[ref_time_col].iloc[0] if ref_time_col in sub else sub[time_col].max()
        ref_time = pd.to_datetime(ref_time)
        sub[time_col] = pd.to_datetime(sub[time_col])

        # Compute time difference (hours) from reference
        sub['delta_h'] = (ref_time - sub[time_col]).dt.total_seconds() / 3600

        # Select only the last N_BINS * N_HOURS window
        sub = sub[sub['delta_h'] >= 0]
        sub = sub[sub['delta_h'] <= N_BINS * N_HOURS]

        # Bin index: 0 (oldest) to N_BINS-1 (most recent)
        sub['bin'] = (sub['delta_h'] // N_HOURS).astype(int)
        sub['bin'] = N_BINS - 1 - sub['bin']  # invert order (bin2 = most recent)

        # Aggregate by bin
        agg = sub.groupby('bin')[value_cols].agg(['mean','min','max','std'])
        agg.columns = ['_'.join([c, stat, f'bin{b}'])
                       for b in agg.index for c in value_cols for stat in ['mean','min','max','std']][:len(agg.columns)]
        agg['hadm_id'] = hadm
        results.append(agg.reset_index(drop=True))

    if results:
        return pd.concat(results, ignore_index=True)
    else:
        return pd.DataFrame()


# PARAMETERS
# ---------------------------

N_HOURS = 6          # length of each bin (hours)
N_BINS = 3           # number of temporal bins
AGG_FUN = 'mean'                # aggregation per bin

# loading in csv files

datapath = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/DEMO CSV Files/';

admissions = load_filtered_csv('ADMISSIONS.csv', usecols=['subject_id','hadm_id','admittime','admission_type','religion','marital_status','ethnicity'])
patients = load_filtered_csv('PATIENTS.csv', usecols=['subject_id','gender','dob'])

print(admissions.columns.tolist())

# for FUTURE:  add randomized times
admissions['admittime'] = pd.to_datetime(admissions['admittime'])
patients['dob'] = pd.to_datetime(patients['dob'])
merged_static = admissions.merge(patients, on='subject_id', how='left')
merged_static['admittime'] = pd.to_datetime(merged_static['admittime'], errors='coerce')
merged_static['dob'] = pd.to_datetime(merged_static['dob'], errors='coerce')

# Compute age in days
#delta = (merged_static['admittime'] - merged_static['dob']).dt.total_seconds() / (3600 * 24)
#merged_static['age'] = delta / 365.25

# Cap maximum age to 90 (MIMIC policy)
# merged_static.loc[merged_static['age'] > 90, 'age'] = 90
static_features_table = merged_static[['hadm_id','gender','admission_type','ethnicity']]
# static_features = merged_static[['hadm_id','age','gender','admission_type','ethnicity']]

print(static_features_table)

# Converting categorical bits of static_features into vectors

# creating reference times for each hadm_id
# ~~ currently just time of latest entry, but will want to randomize in the future

# Ensure datetime conversion
df = load_filtered_csv('CHARTEVENTS.csv', usecols=['hadm_id','charttime'])
hadm_col='hadm_id'
time_col='charttime'
#print(df)

df = df.copy()
df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
df = df.dropna(subset=[hadm_col, time_col])

# Group and get the latest time per admission
ref_times = (
    df.groupby(hadm_col, as_index=False)[time_col]
      .max()
      .rename(columns={time_col: 'ref_time'})
)

print(ref_times)

# finding the hadm-ids of similar items (i.e. "heart rate" and "heart rates")

import re

def find_itemids_by_label(df, keywords, case_insensitive=True, fuzzy=False):
    """
    Search D_ITEMS or D_LABITEMS for ITEMIDs whose LABEL or ABBREVIATION
    matches one or more given keywords.

    Parameters
    ----------
    dictionary_path : str
        Path to D_ITEMS.csv or D_LABITEMS.csv
    keywords : list of str
        Words/phrases to search for (e.g. ['heart rate', 'pulse'])
    case_insensitive : bool
        If True, match regardless of case.
    fuzzy : bool
        If True, use substring matching with word boundaries (slower but catches variations).

    Returns
    -------
    matches : pd.DataFrame
        Subset of the dictionary with matching ITEMIDs and LABELs
    """

    # Build regex pattern
    flags = re.IGNORECASE if case_insensitive else 0
    if fuzzy:
        pattern = '|'.join([fr'\b{re.escape(k)}\b' for k in keywords])
    else:
        pattern = '|'.join([re.escape(k) for k in keywords])

    # Combine label/abbreviation/description fields if they exist
    text_cols = [c for c in ['label', 'abbreviation', 'category', 'param_type', 'fluid', 'specimen'] if c in df.columns]
    df['search_text'] = df[text_cols].astype(str).agg(' '.join, axis=1)

    # Search
    mask = df['search_text'].str.contains(pattern, flags=flags, regex=True)
    matches = df[mask].copy()

    # Keep key columns
    keep_cols = [c for c in ['itemid','label','abbreviation','category','fluid','specimen'] if c in matches.columns]
    matches = matches[keep_cols].drop_duplicates(subset=['itemid'])

    # Sort alphabetically for readability
    return matches.sort_values('label').reset_index(drop=True)

# Time bin data helper functions

# loads in the temporal data sets
def load_temporal_table(filename, usecols, time_col, value_col, item_col=None, itemids=None, header=1):
    """
    Loads and prepares a temporal table (like CHARTEVENTS or LABEVENTS).
    Optionally maps ITEMIDs to meaningful labels.
    """
    path = f"{datapath}/{filename}"
    df = pd.read_csv(path, usecols=usecols, header=header, low_memory=False)
    df.columns = df.columns.str.strip().str.lower()

     # Filter by hadm_id
    df = df[df['hadm_id'].isin(training_id)]

    # Filter by itemids if provided
    if itemids is not None:
        # itemids might be a pandas Series or list; ensure it's a list
        itemid_list = list(itemids)
        df = df[df[item_col].isin(itemid_list)]

    # Convert to datetime
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
    df = df.dropna(subset=[time_col, value_col])

    return df


# can split to 3 timebins, find mean, max, min, and change between time bins
# will output NaN value does not exist
def bin_and_average(df, time_col, value_col, hadm_col='hadm_id', ref_time_col=None, AGG_FUN=('mean','max'), prefix=None, add_trend=True):
    """
    Aggregates a temporal dataframe into N_BINS × BIN_HOURS windows before ref_time_col.
    Returns per-hadm_id averaged values per bin.
    """
    results = []
    name_prefix = prefix if prefix else value_col

    # Pre-build output column names
    feature_cols = [hadm_col]
    for fun in AGG_FUN:
        for b in range(N_BINS):
            feature_cols.append(f'{name_prefix}_bin{b+1}_{fun}')
        if add_trend and fun == 'mean':
            for b in range(1, N_BINS):
                feature_cols.append(f'change_{name_prefix}_bin{b+1}_{fun}')

    # Empty or invalid DataFrame case
    if df is None or df.empty or not all(c in df.columns for c in [hadm_col, time_col, value_col]):
        print(f"⚠️ No valid data for {name_prefix}, returning NaN-filled feature table.")
        return pd.DataFrame(columns=feature_cols)

    # If ref_time_col not given, use last available time as reference
    if ref_time_col is None:
        df['ref_time'] = df.groupby(hadm_col)[time_col].transform('max')
        ref_time_col = 'ref_time'

    for hadm, sub in df.groupby(hadm_col):

        # Skip if subset empty or invalid
        if sub.empty or sub[value_col].dropna().empty:
            continue

        ref_time = pd.to_datetime(sub[ref_time_col].iloc[0])
        if pd.isna(ref_time):
            continue

        sub[time_col] = pd.to_datetime(sub[time_col])
        sub = sub.dropna(subset=[time_col, value_col])
        if sub.empty:
            continue

        # Calculate how many hours before reference
        sub['delta_h'] = (ref_time - sub[time_col]).dt.total_seconds() / 3600
        sub = sub[(sub['delta_h'] >= 0) & (sub['delta_h'] <= N_BINS * N_HOURS)]
        if sub.empty:
            # Fill with NaNs for all bins
            row = {hadm_col: hadm}
            name_prefix = prefix if prefix else value_col
            for fun in AGG_FUN:
                for b in range(N_BINS):
                    row[f'{name_prefix}_bin{b+1}_{fun}'] = np.nan
                if add_trend and fun == 'mean':
                    for b in range(1, N_BINS):
                        row[f'change_{name_prefix}_bin{b+1}_{fun}'] = np.nan
            results.append(row)
            continue

        # Compute bin index
        sub['bin'] = np.floor(sub['delta_h'] / N_HOURS).astype(int)
        sub['bin'] = N_BINS - 1 - sub['bin']  # bin2 = most recent

        row = {hadm_col: hadm}
        name_prefix = prefix if prefix else value_col

        # Aggregate per bin
        for fun in AGG_FUN:
            bin_stats = sub.groupby('bin')[value_col].agg(fun)
            for b in range(N_BINS):
                row[f'{prefix}_bin{b+1}_{fun}'] = bin_stats.get(b, np.nan)

            # add trend only for mean
            if add_trend and fun == 'mean':
                for b in range(1, N_BINS):
                    prev = bin_stats.get(b-1, np.nan)
                    curr = bin_stats.get(b, np.nan)
                    delta = curr - prev if pd.notna(curr) and pd.notna(prev) else np.nan
                    row[f'change_{prefix}_bin{b+1}_{fun}'] = delta

        results.append(row)

    # If all groups were empty
    if not results:
        print(f"⚠️ No valid data found for {prefix or value_col}. Returning NaN-filled table.")
        return pd.DataFrame(columns=feature_cols)
    else:
      df_out = pd.DataFrame(results)
      df_out = df_out.groupby('hadm_id').mean(numeric_only=True).reset_index()
      return df_out

# generating arrays of ids for vitals
d_items = load_filtered_csv('D_ITEMS.csv', usecols=['itemid','label'])

heart_ids = find_itemids_by_label(d_items, keywords=['heart rate','atrial rate'], fuzzy=True)
# print(heart_ids)
heart_ids1 = [211,220045];
# print(heart_ids)

sbp_ids = find_itemids_by_label(d_items, ['blood pressure','systolic'])
# print(sbp_ids)
sbp_ids1 = [6,225309,6701,51,220052,3313,3315,3317,3321,3323,480,482]

dbp_ids = find_itemids_by_label(d_items, ['blood pressure','diastolic'])
# print(dbp_ids)
dbp_ids1 = [8364,225310,8555,8368,220051,8502,8503,8504,8505,8506,8507,8444,8445,8446]

temp_ids = find_itemids_by_label(d_items, ['temperature','temp'])
# print(temp_ids)
temp_ids1 = [676,677,223762]

spo2_ids = find_itemids_by_label(d_items, ['spo2','oxygen saturation'])
# print(spo2_ids)
spo2_ids1 = [228232,646,6719]

MAP_ids = find_itemids_by_label(d_items, ['map','mean arterial pressure'])
# print(MAP_ids)
MAP_ids1 = [6399, 2309, 2544, 2974, 3067, 6605, 1199, 2522, 6579,438,2369,1321,2770,5804]


# FOR FUTURE - partially manually done, so may not emcompass all the applicable itemid's of a larger dataset... need to find a better system

# putting together temporal bins for vitals

# PULSE
vitals = load_temporal_table(
    filename='CHARTEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=heart_ids1
)

# (c) average across all heart-rate-type ITEMIDs per time
vitals_grouped = vitals.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()

# (d) bin into temporal windows
heart_features = bin_and_average(vitals_grouped, time_col='charttime', value_col='valuenum', prefix="pulse")

print(heart_features.head())


# SYS BLOOD PRESSURE
vitals = load_temporal_table(
    filename='CHARTEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=sbp_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()

# (d) bin into temporal windows
sys_bp_features = bin_and_average(vitals_grouped, time_col='charttime', value_col='valuenum', prefix="sys_bp")

print(sys_bp_features.head())


# DIAS BLOOD PRESSURE
vitals = load_temporal_table(
    filename='CHARTEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=dbp_ids1
)

# (c)  get rid of duplicate entries
vitals_grouped = vitals.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()

# (d) bin into temporal windows
dias_bp_features = bin_and_average(vitals_grouped, time_col='charttime', value_col='valuenum', prefix="dias_bp")

print(dias_bp_features.head())


# MAP
vitals = load_temporal_table(
    filename='CHARTEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=MAP_ids1
)

# (c)  get rid of duplicate entries
vitals_grouped = vitals.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
print(vitals_grouped)

# (d) bin into temporal windows
MAP_features = bin_and_average(vitals_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean','min'), prefix="MAP")

print(MAP_features.head())


# TEMP
vitals = load_temporal_table(
    filename='CHARTEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=temp_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()

# (d) bin into temporal windows
temp_features = bin_and_average(vitals_grouped, time_col='charttime', value_col='valuenum', prefix="temp")

print(temp_features.head())


# SPO2
vitals = load_temporal_table(
    filename='CHARTEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=spo2_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()

# (d) bin into temporal windows
spo2_features = bin_and_average(vitals_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean','min'), prefix="spo2")

print(spo2_features.head())

# combining all vitals feature tables into a single one

from functools import reduce

vitals_features = [heart_features, sys_bp_features, dias_bp_features, MAP_features, temp_features, spo2_features]

vitals_feature_table = reduce(
    lambda left, right: pd.merge(left, right, on='hadm_id', how='outer'),  vitals_features)

# print(vitals_feature_table)
list(vitals_feature_table.columns)

# calculating MAP if empty, and if blood pressure is given

# vitals_feature_table1 = vitals_feature_table.copy()

# timebin 1
map_cols = [c for c in vitals_feature_table.columns if "MAP_bin1_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin1_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin1_mean" in c]

print(map_cols, sbp_cols, dbp_cols)

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):
    print(map_col, sbp_col, dbp_col)

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# time bin2

map_cols = [c for c in vitals_feature_table.columns if "MAP_bin2_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin2_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin2_mean" in c]

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# time bin 3

map_cols = [c for c in vitals_feature_table.columns if "MAP_bin3_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin3_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin3_mean" in c]

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# change in MAP

map1_cols = [c for c in vitals_feature_table.columns if "MAP_bin1_mean" in c]
map2_cols = [c for c in vitals_feature_table.columns if "MAP_bin2_mean" in c]
map3_cols = [c for c in vitals_feature_table.columns if "MAP_bin3_mean" in c]

dmap2_cols = [c for c in vitals_feature_table.columns if "change_MAP_bin2_mean" in c]
dmap3_cols = [c for c in vitals_feature_table.columns if "change_MAP_bin3_mean" in c]

for map1_col, map2_col, map3_col, dmap2_col, dmap3_col in zip(map1_cols, map2_cols, map3_cols, dmap2_cols, dmap3_cols):

    # change between time bins 1 and 2
    mask2 = vitals_feature_table[dmap2_col].isna() & \
           vitals_feature_table[map1_col].notna() & \
           vitals_feature_table[map2_col].notna()

    # change between time bins 2 and 3
    mask3 = vitals_feature_table[dmap3_col].isna() & \
           vitals_feature_table[map2_col].notna() & \
           vitals_feature_table[map3_col].notna()

    vitals_feature_table.loc[mask2, dmap2_col] = (
        vitals_feature_table.loc[mask, map2_col] -
        vitals_feature_table.loc[mask, map1_col])

    vitals_feature_table.loc[mask3, dmap3_col] = (
        vitals_feature_table.loc[mask, map3_col] -
        vitals_feature_table.loc[mask, map2_col])


# print(vitals_feature_table['MAP_bin1_mean'])
list(vitals_feature_table.columns)

# finding itemids for lab

d_lab = load_filtered_csv('D_LABITEMS.csv', usecols=['itemid','label','fluid','category'])

# CREATININE - urine
lab_keywords = ['creatinine']
creatinine_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(creatinine_ids)
creatinine_ids1 = [51067,51080,51081,51006]

# WBC - urine + blood
lab_keywords = ['wbc','white blood']
wbc_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(wbc_ids)
wbc_urine_ids1 = [51516,51517,51518]
wbc_blood_ids1 = [51300]

# LACTATE
lab_keywords = ['lactate']
lactate_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(lactate_ids)
lactate_ids1 = [50813]

# BUN - blood urea nitrogran
lab_keywords = ['nitrogen','urea','bun']
BUN_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(BUN_ids)
BUN_ids1 = [51006]

# AST - aspartate aminotransferase
lab_keywords = ['aspartate','aminotransferase', 'ast']
AST_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(AST_ids)
AST_ids1 = [50878]

# ALT - alanine aminotransferase
ALT_ids1 = [50861]

# BILIRUBIN - urine + blood direct / total
lab_keywords = ['bilirubin']
bilirubin_urine_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(bilirubin_ids)
bilirubin_urine_ids1 = [51464,51465]
bilirubin_dir_ids1 = [50883]
bilirubin_tot_ids1 = [50885]

# GLUCOSE - urine + blood
lab_keywords = ['glucose']
gluc_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(gluc_ids)
gluc_blood_ids1 = [50809,50931,51529]
gluc_urine_ids1 = [51478,51084]

# Na - blood + urine
lab_keywords = ['na','sodium']
Na_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(Na_ids)
Na_blood_ids1 = [50983,50824]
Na_urine_ids1 = [51100]

# K - blood + urine
lab_keywords = ['k','potassium']
pott_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(pott_ids)
pott_blood_ids1 = [50971,50822]
pott_urine_ids1 = [51097]

# BICARBONATE - blood + urine
lab_keywords = ['bicarbonate','bicarb']
bicarb_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(bicarb_ids)
bicarb_blood_ids1 = [50882,50803]
bicarb_urine_ids1 = [51076]

# HEMOGLOBIN
lab_keywords = ['hemoglobin']
hemoglob_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(hemoglob_ids)
hemoglob_ids1 = [50811,51222]

# PLATELETS
lab_keywords = ['platelets']
platelets_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(platelets_ids)
platelets_ids1 = [51240]

# blood pH
lab_keywords = ['pH']
blood_pH_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
# print(blood_pH_ids)
blood_pH_ids1 = [50820]

# blood CO2
lab_keywords = ['pCO2']
blood_pCO2_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(blood_pCO2_ids)
blood_pCO2_ids1 = [50818]

# blood O2
lab_keywords = ['pO2']
blood_pO2_ids = find_itemids_by_label(d_lab, lab_keywords, fuzzy=True)
#print(blood_pO2_ids)
blood_pO2_ids1 = [50821]

# turning lab stuff into temporal bins

# WBC urine
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','itemid','charttime','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=wbc_urine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
WBC_urine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="WBC_urine",)
#print(WBC_urine_features.head())

# WBC blood
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=wbc_blood_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
WBC_blood_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="WBC_blood",)
#print(WBC_blood_features.head())

# Lactate
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=lactate_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
lactate_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="lactate",)
#print(lactate_features.head())

# Creatinine
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=creatinine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
creatinine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="creatinine",)
#print(creatinine_features.head())

# BUN
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=BUN_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
BUN_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="BUN",)
#print(BUN_features.head())

# AST
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=AST_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
AST_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="AST",)
#print(AST_features.head())

# ALT
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=ALT_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
ALT_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="ALT",)
#print(ALT_features.head())

# BILIRUBIN - urine / dir / tot
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=bilirubin_urine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
bili_urine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="bili_urine",)
#print(bili_urine_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=bilirubin_dir_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
bili_dir_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="bili_dir",)
#print(bili_dir_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=bilirubin_tot_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
bili_tot_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="bili_tot",)
#print(bili_tot_features.head())

# GLUCOSE - urine / blood
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=gluc_urine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
gluc_urine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="gluc_urine",)
#print(gluc_urine_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=gluc_blood_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
gluc_blood_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="gluc_blood",)
#print(gluc_blood_features.head())

# Na - urine / blood
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=Na_urine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
Na_urine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="Na_urine",)
#print(Na_urine_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=Na_blood_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
Na_blood_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="Na_blood",)
#print(Na_blood_features.head())

# K - urine / blood
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=pott_urine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
pott_urine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="pott_urine",)
#print(pott_urine_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=pott_blood_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
pott_blood_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="pott_blood",)
#print(pott_blood_features.head())

# BICARBONATE - urine/blood
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=bicarb_urine_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
bicarb_urine_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="bicarb_urine",)
#print(bicarb_urine_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=bicarb_blood_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
bicarb_blood_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="bicarb_blood",)
#print(bicarb_blood_features.head())

# HEMOGLOBIN
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=hemoglob_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
hemoglob_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="hemoglob",)
#print(hemoglob_features.head())

# PLATELETS
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=platelets_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
platelets_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="platelets",)
#print(platelets_features.head())

# pH, pCO2, pO2
labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=blood_pH_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
blood_pH_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="blood_pH",)
#print(blood_pH_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=blood_pCO2_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
blood_pCO2_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="blood_pCO2",)
#print(blood_pCO2_features.head())

labs = load_temporal_table(
    filename='LABEVENTS.csv',
    usecols=['hadm_id','charttime','itemid','valuenum'],
    time_col='charttime',
    value_col='valuenum',
    item_col='itemid',
    itemids=blood_pO2_ids1
)
labs_grouped = labs.groupby(['hadm_id','charttime'])['valuenum'].mean().reset_index()
blood_pO2_features = bin_and_average(labs_grouped, time_col='charttime', value_col='valuenum', AGG_FUN=('mean',), prefix="blood_pO2",)
#print(blood_pO2_features.head())

# combining the lab stuff into 1 feature table

labs_features = [WBC_urine_features,WBC_blood_features,lactate_features,creatinine_features,BUN_features,
                 AST_features,ALT_features,bili_urine_features,bili_dir_features,bili_tot_features,
                 gluc_urine_features,gluc_blood_features,Na_urine_features,Na_blood_features,pott_urine_features,
                 pott_blood_features,bicarb_urine_features,bicarb_blood_features,hemoglob_features,
                 platelets_features,blood_pH_features,blood_pCO2_features,blood_pO2_features,]

labs_feature_table = reduce(
    lambda left, right: pd.merge(left, right, on='hadm_id', how='outer'),  labs_features)

print(labs_feature_table)

# Microbiology IDs
# ~~ no need to do bins ~~

micro = pd.read_csv(
    f"{datapath}/MICROBIOLOGYEVENTS.csv",
    usecols=['hadm_id','spec_type_desc','org_name','ab_name','interpretation',],
    header=1,low_memory=False
)
micro = micro[micro['hadm_id'].isin(training_id)]
micro['interpretation'] = micro['interpretation'].str.strip().str.upper()

# Keep valid interpretations (S, I, R) / removing NULLS
micro = micro[micro['interpretation'].isin(['S', 'I', 'R'])]

# Flag resistant (R) and intermediate (I)
micro['is_resistant'] = (micro['interpretation'] == 'R').astype(int)
micro['is_intermediate'] = (micro['interpretation'] == 'I').astype(int)

# If microorganisms found
culture_presence = (
    micro.groupby('hadm_id')['org_name'].nunique().reset_index(name='num_organisms')
)
culture_presence['any_pos_culture'] = (culture_presence['num_organisms'] > 0).astype(int)

# Proportion of resistant antibiotics among all tested
resistance_summary = (
    micro.groupby('hadm_id')['is_resistant'].mean().reset_index(name='prop_resist')
)

# Count of total antibiotics tested
num_tests = (
    micro.groupby('hadm_id')['interpretation'].count().reset_index(name='num_antibiotics')
)

# Mean proportion of intermediate results
intermediate_summary = (
    micro.groupby('hadm_id')['is_intermediate'].mean().reset_index(name='prop_intermed')
)

# creating feature table
micro_features_table = (
    culture_presence
    .merge(resistance_summary, on='hadm_id', how='outer')
    .merge(intermediate_summary, on='hadm_id', how='outer')
    .merge(num_tests, on='hadm_id', how='outer')
)

# fill NaNs for patients with no microbiology data
micro_features_table[['num_organisms','any_pos_culture','prop_resist','prop_intermed','num_antibiotics']] = \
    micro_features_table[['num_organisms','any_pos_culture','prop_resist','prop_intermed','num_antibiotics']].fillna(0)

print(micro_features_table)

# helper function for finding overall across 3 time bins

def summarize_over_window(df,ref_times,hadm_col='hadm_id',time_col='charttime',value_col='valuenum',
    BIN_HOURS=N_HOURS, N_BIN=N_BINS, AGG_FUN=('mean', 'max'), prefix='NONE',
fill_missing=True
):
    """
    Summarize time-series data over the total time span of N_BINS × BIN_HOURS hours
    before each reference time (ref_time) for each admission.

    Parameters
    ----------
    df : pd.DataFrame
        Must include hadm_id, time_col, and value_col.
    ref_times : pd.DataFrame
        Must include hadm_id and ref_time (e.g., last charttime or admittime).
    hadm_col, time_col, value_col : str
        Column names for admission ID, timestamp, and numeric value.
    BIN_HOURS, N_BINS : int
        The number of bins and their width — defines total window length.
    agg_funs : tuple
        Aggregation functions (e.g., ('mean','sum','max','min')).
    prefix : str
        Prefix for output feature column names.
    fill_missing : bool
        If True, returns zero/NaN-filled rows for missing hadm_ids.

    Returns
    -------
    pd.DataFrame
        One row per hadm_id with aggregated features.
    """

    df = df.copy()
    ref_times = ref_times.copy()

    # Normalize column names
    df.columns = df.columns.str.strip().str.lower()
    ref_times.columns = ref_times.columns.str.strip().str.lower()
    hadm_col = hadm_col.lower()
    time_col = time_col.lower()
    value_col = value_col.lower()

    # Safety checks
    for col in [hadm_col, time_col, value_col]:
        if col not in df.columns:
            raise KeyError(f"Column '{col}' not found in df: {df.columns.tolist()}")
    if hadm_col not in ref_times.columns:
        raise KeyError(f"Column '{hadm_col}' not found in ref_times: {ref_times.columns.tolist()}")

    # Ensure datetimes
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
    ref_times['ref_time'] = pd.to_datetime(ref_times['ref_time'], errors='coerce')

    # Merge reference times
    merged = df.merge(ref_times[[hadm_col, 'ref_time']], on=hadm_col, how='right')

    # Calculate time difference
    merged['delta'] = (merged['ref_time'] - merged[time_col]).dt.total_seconds() / 3600.0

    # Filter valid time window
    merged = merged[(merged['delta'] >= 0) & (merged['delta'] <= BIN_HOURS * N_BIN)]

    if merged.empty:
        print("⚠️ No matching rows found for time window; returning empty feature table.")
        out = ref_times[[hadm_col]].copy()
        for fun in AGG_FUN:
            out[f'{prefix}_{fun}'] = np.nan
        return out

    # Group and aggregate
    grouped = merged.groupby(hadm_col)[value_col].agg(AGG_FUN).reset_index()

    # Rename output columns
    grouped.columns = [hadm_col] + [f"{prefix}_{f}" for f in AGG_FUN]

    # Optionally include all hadm_ids (even those without data)
    if fill_missing:
        grouped = ref_times[[hadm_col]].merge(grouped, on=hadm_col, how='left').fillna(0)

    return grouped

# getting inputevent itemids that correspond to fluid intake

d_items = pd.read_csv(f"{datapath}/D_ITEMS.csv", header=1, low_memory=False)
d_items.columns = d_items.columns.str.strip().str.lower()

# Filter for fluids in inputevents tables
fluids = d_items[
    ((d_items['category'] == 'Fluids/Intake') | (d_items['category'] == 'Fluids - Other (Not In Use)')) &
    (d_items['linksto'].str.contains('inputevents', case=False, na=False))
].copy()

# Sort and clean
fluids_ids = fluids[['itemid', 'label', 'category', 'linksto']].sort_values('label')
#print(fluids_ids)

# Making input tables across all time bins

# loading both INPUTEVENTS_MV and INPUTEVENTS_CV - just looking at IV fluid inputs

cols_mv = ['hadm_id', 'endtime', 'itemid', 'amount', 'amountuom']
input_mv = pd.read_csv(
    f"{datapath}/INPUTEVENTS_MV.csv", usecols=cols_mv, header=1,low_memory=False)
  # endtime will be used as charttime
if 'endtime' in input_mv.columns:
    input_mv.rename(columns={'endtime': 'charttime'}, inplace=True)
#print(input_mv)

cols_cv = ['hadm_id', 'charttime', 'itemid', 'amount', 'amountuom']
input_cv = pd.read_csv(
    f"{datapath}/INPUTEVENTS_CV.csv", usecols=cols_cv, header=1,low_memory=False)
#print(input_cv)


# Normalize column names
input_mv.columns = input_mv.columns.str.strip().str.lower()
input_cv.columns = input_cv.columns.str.strip().str.lower()

# Ensure consistent dtypes
for df in [input_mv, input_cv]:
    df['hadm_id'] = pd.to_numeric(df['hadm_id'], errors='coerce')
    df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
#    df['charttime'] = pd.to_datetime(df['charttime'], errors='coerce')
#    df.dropna(subset=['hadm_id', 'charttime', 'amount'], inplace=True)
    df['hadm_id'] = df['hadm_id'].astype(int)

# Combine them
input_combined = pd.concat([input_mv, input_cv], axis=0, ignore_index=True)
input_combined_training = input_combined[input_combined['hadm_id'].isin(training_id)]
#print(input_combined_training)


#print(fluids_ids)
input_combined_training = input_combined_training[input_combined_training['itemid'].isin(fluids_ids['itemid'])]
#print(input_combined_training)

#print(ref_times)

input_combined_training.columns = input_combined_training.columns.str.strip().str.lower()
ref_times.columns = ref_times.columns.str.strip().str.lower()
ref_times['hadm_id'] = pd.to_numeric(ref_times['hadm_id'], errors='coerce').astype('Int64')


# Extract overall timebins feature
input_features_table = summarize_over_window(
    df=input_combined_training,
    ref_times=ref_times,
    hadm_col='hadm_id',
    time_col='charttime',
    value_col='amount',
    BIN_HOURS=N_HOURS,       # each bin = 2 hr
    N_BIN=N_BINS,          # 3 bins = total 6 hr window
    AGG_FUN=('sum',), # total fluid input volume
    prefix='input',
    fill_missing=True
)
print(input_features_table)

# Finding output ids for

# OUTPUT
output_keywords = ['urine out']
outputs_ids = find_itemids_by_label(d_items, output_keywords, fuzzy=True)
print(outputs_ids)
# lactate_ids1 = [50813]

# loading output values

# outputs = load_temporal_table(
#     filename='OUTPUTEVENTS.csv',
#     usecols=['hadm_id','charttime','itemid','valueuom'],
#     time_col='charttime',
#     value_col='value',
#     item_col='itemid',
#     itemids=outputs_ids
# )

# need to find sum across time bin
cols_out = ['hadm_id', 'itemid', 'charttime', 'value']
outputs = pd.read_csv(
    f"{datapath}/OUTPUTEVENTS.csv", usecols=cols_out, header=1,low_memory=False)

outputs_features_table = summarize_over_window(
    df=outputs,
    ref_times=ref_times,
    hadm_col='hadm_id',
    time_col='charttime',
    value_col='value',
    BIN_HOURS=N_HOURS,       # each bin = 2 hr
    N_BIN=N_BINS,          # 3 bins = total 6 hr window
    AGG_FUN=('sum',), # total fluid input volume
    prefix='outputs',
    fill_missing=True
)
print(outputs_features_table)

# COMBINING ALL INTO SINGLE

static_features_table['hadm_id'] = pd.to_numeric(static_features_table['hadm_id'], errors='coerce').astype('Int64')
vitals_feature_table['hadm_id'] = pd.to_numeric(vitals_feature_table['hadm_id'], errors='coerce').astype('Int64')
labs_feature_table['hadm_id'] = pd.to_numeric(labs_feature_table['hadm_id'], errors='coerce').astype('Int64')
micro_features_table['hadm_id'] = pd.to_numeric(micro_features_table['hadm_id'], errors='coerce').astype('Int64')
input_features_table['hadm_id'] = pd.to_numeric(input_features_table['hadm_id'], errors='coerce').astype('Int64')
outputs_features_table['hadm_id'] = pd.to_numeric(outputs_features_table['hadm_id'], errors='coerce').astype('Int64')


all_features = [static_features_table, vitals_feature_table, labs_feature_table, micro_features_table, input_features_table, outputs_features_table]

all_features_table = reduce(
    lambda left, right: pd.merge(left, right, on='hadm_id', how='outer'),  all_features)

#print(all_features_table)
all_features_table.head()

#all_features_table.to_csv(f"{datapath}/all_features_table.csv", index=False)

# Embedding the text columns - gender, admission type, ethnicity

import pandas as pd

df = all_features_table.copy()

# Columns to encode
categorical_cols = ["gender", "ethnicity", "admission_type"]

# Ensure they are hashable (strings)
for col in categorical_cols:
    df[col] = df[col].astype(str)

# One-hot encode
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=False)

df_encoded.head()
#print(df_encoded)

df_encoded.to_csv(f"{datapath}/all_features_table_encoded.csv", index=False)

"""# New Section"""