# -*- coding: utf-8 -*-
"""SeniorProject499.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MK2imPPqFCh4u5qFrNzZ26Qt8MiILYy
"""

# connecting to the drive

from google.colab import drive
drive.mount('/content/drive')

"""# Preprocessing Structured Data - Selena

"""

# adding path to CSVs

import csv
import pandas as pd
import numpy as np
from datetime import timedelta
import os

!ls '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files'

datapath = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files/';

# PARAMETERS
# ---------------------------

N_HOURS = 6          # length of each bin (hours)
N_BINS = 3           # number of temporal bins
AGG_FUN = 'mean'                # aggregation per bin

# create vectors to store hadm-id's we want to use for training

def remove_duplicates(arr):
    """Remove duplicate values from an array while preserving order."""
    seen = set()
    unique = []
    for x in arr:
        if x not in seen:
            unique.append(x)
            seen.add(x)
    return unique


# get list of hadmids from list of subject ids Rachael provided
path = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/train_small_subject_ids.csv'
subject_ids = pd.read_csv(path).iloc[:, 0].tolist()
#print(subject_ids)

path = f"{datapath}/{'ADMISSIONS.csv'}"
admissions = pd.read_csv(path);
#print(admissions)
training_id = ( admissions.loc[admissions["SUBJECT_ID"].astype(int).isin(subject_ids), "HADM_ID"]
    .unique().tolist())

# training_id = set(training_set.astype("Int64").astype(str))
# print(training_set)
print(len(training_id))
print(len(subject_ids))


# Demo list of training_ids

# HELPER FUNCTIONS
# ---------------------------

# def load_filtered_csv(filename, usecols=None):
#     """Load CSV, keep only rows with HADM_ID in training_id."""
#     path = f"{datapath}/{filename}"

#     dtype_overrides = {
#         'SUBJECT_ID': 'string',
#         'HADM_ID': 'string',
#         'ICUSTAY_ID': 'string',
#         'ITEMID': 'string',
#         'ROW_ID': 'string',
#         'DOB': 'string'
#     }

#     df = pd.read_csv(path, usecols=usecols, dtype=dtype_overrides)
#     df.columns = df.columns.str.strip().str.upper()
#     if 'HADM_ID' in df.columns:
#         df = df[df['HADM_ID'].isin([str(x) for x in training_id])]
#     return df

# loading it in chunks for lower memory
def load_filtered_csv_stream(
    filename,
    training_id,
    usecols=None,
    chunksize=300_000
):
    """
    Stream CSV in chunks and keep only rows with HADM_ID in training_id.
    """

    path = f"{datapath}/{filename}"

    # Convert once for fast lookup
    training_id_set = set(str(x) for x in training_id)

    dtype_overrides = {
        'SUBJECT_ID': 'string',
        'HADM_ID': 'string',
        'ICUSTAY_ID': 'string',
        'ITEMID': 'string',
        'ROW_ID': 'string',
        'DOB': 'string'
    }

    filtered_chunks = []

    for chunk in pd.read_csv(
        path,
        usecols=usecols,
        dtype=dtype_overrides,
        chunksize=chunksize,
        low_memory=False
    ):
        # Normalize column names per chunk
        chunk.columns = chunk.columns.str.strip().str.upper()

        # Filter only if HADM_ID exists
        if 'HADM_ID' in chunk.columns:
            chunk = chunk[chunk['HADM_ID'].isin(training_id_set)]

        if not chunk.empty:
            filtered_chunks.append(chunk)

    if not filtered_chunks:
        return pd.DataFrame(columns=usecols)

    return pd.concat(filtered_chunks, ignore_index=True)


# put things into time bins
def aggregate_in_bins(df, time_col, value_cols, ref_time_col='REF_TIME'):
    """Bin events into N_HOURS windows relative to ref_time_col."""
    results = []

    for hadm, sub in df.groupby('HADM_ID'):
        ref_time = sub[ref_time_col].iloc[0] if ref_time_col in sub else sub[time_col].max()
        ref_time = pd.to_datetime(ref_time)
        sub[time_col] = pd.to_datetime(sub[time_col])

        # Compute time difference (hours) from reference
        sub['delta_h'] = (ref_time - sub[time_col]).dt.total_seconds() / 3600

        # Select only the last N_BINS * N_HOURS window
        sub = sub[sub['delta_h'] >= 0]
        sub = sub[sub['delta_h'] <= N_BINS * N_HOURS]

        # Bin index: 0 (oldest) to N_BINS-1 (most recent)
        sub['bin'] = (sub['delta_h'] // N_HOURS).astype(int)
        sub['bin'] = N_BINS - 1 - sub['bin']  # invert order (bin2 = most recent)

        # Aggregate by bin
        agg = sub.groupby('bin')[value_cols].agg(['mean','min','max','std'])
        agg.columns = ['_'.join([c, stat, f'bin{b}'])
                       for b in agg.index for c in value_cols for stat in ['mean','min','max','std']][:len(agg.columns)]
        agg['HADM_ID'] = hadm
        results.append(agg.reset_index(drop=True))

    if results:
        return pd.concat(results, ignore_index=True)
    else:
        return pd.DataFrame()


# function to help with saving files while running thru each section

import os, glob

OUTDIR = f"{datapath}/checkpoints"
os.makedirs(OUTDIR, exist_ok=True)

def save_section(df, name):
    path = f"{OUTDIR}/{name}.parquet"   # parquet is faster/smaller than csv
    df.to_parquet(path, index=False)
    print("saved", path)

# loading in csv files

admissions = load_filtered_csv_stream('ADMISSIONS.csv', training_id, usecols=['SUBJECT_ID','HADM_ID','ADMITTIME','ADMISSION_TYPE','ETHNICITY'])
patients = load_filtered_csv_stream('PATIENTS.csv', training_id, usecols=['SUBJECT_ID','GENDER','DOB'])

print(admissions.columns.tolist())

# for FUTURE:  add randomized times
admissions['ADMITTIME'] = pd.to_datetime(admissions['ADMITTIME'])
patients['DOB'] = pd.to_datetime(patients['DOB'])
merged_static = admissions.merge(patients, on='SUBJECT_ID', how='left')
merged_static['ADMITTIME'] = pd.to_datetime(merged_static['ADMITTIME'], errors='coerce')
merged_static['DOB'] = pd.to_datetime(merged_static['DOB'], errors='coerce')

# Compute age in years
merged_static['AGE'] = ( merged_static["ADMITTIME"].dt.year - merged_static["DOB"].dt.year -
        ((merged_static["ADMITTIME"].dt.month < merged_static["DOB"].dt.month) |
        ((merged_static["ADMITTIME"].dt.month == merged_static["DOB"].dt.month) &
            (merged_static["ADMITTIME"].dt.day < merged_static["DOB"].dt.day)) ).astype(int)
)
#print(merged_static['AGE'])

# Cap maximum age to 90 (MIMIC policy)
# merged_static.loc[merged_static['AGE'] > 90, 'age'] = 90
# static_features_table = merged_static[['HADM_ID','GENDER','ADMISSION_TYPE','ETHNICITY']]
static_features_table = merged_static[['HADM_ID','SUBJECT_ID','AGE','GENDER','ADMISSION_TYPE','ETHNICITY']]

# Columns to encode
categorical_cols = ["GENDER", "ETHNICITY", "ADMISSION_TYPE"]

# Ensure they are hashable (strings)
for col in categorical_cols:
    static_features_table[col] = static_features_table[col].astype(str)

# One-hot encode
static_features_table_encoded = pd.get_dummies(static_features_table, columns=categorical_cols, dtype = int, drop_first=False)

print(static_features_table_encoded)
static_features_table_encoded.to_csv(f"{OUTDIR}/static_features_table.csv", index=False)

# creating reference times for each HADM_ID
# ~~ currently just time of latest entry, but will want to randomize in the future

# Ensure datetime conversion
df = load_filtered_csv_stream('CHARTEVENTS.csv', training_id, usecols=['HADM_ID','CHARTTIME'])
hadm_col='HADM_ID'
time_col='CHARTTIME'
#print(df)

df = df.copy()
df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
df = df.dropna(subset=[hadm_col, time_col])

# Group and get the latest time per admission
ref_times = (
    df.groupby(hadm_col, as_index=False)[time_col]
      .max()
      .rename(columns={time_col: 'REF_TIME'})
)

print(ref_times)
ref_times.to_csv(f"{OUTDIR}/ref_times.csv", index=False);

# finding the hadm-ids of similar items (i.e. "heart rate" and "heart rates")

import re

def find_ITEMIDs_by_LABEL(df, keywords, case_insensitive=True, fuzzy=False):
    """
    Search D_ITEMS or D_LABITEMS for ITEMIDs whose LABEL or ABBREVIATION
    matches one or more given keywords.

    Parameters
    ----------
    dictionary_path : str
        Path to D_ITEMS.csv or D_LABITEMS.csv
    keywords : list of str
        Words/phrases to search for (e.g. ['heart rate', 'pulse'])
    case_insensitive : bool
        If True, match regardless of case.
    fuzzy : bool
        If True, use substring matching with word boundaries (slower but catches variations).

    Returns
    -------
    matches : pd.DataFrame
        Subset of the dictionary with matching ITEMIDs and LABELs
    """

    # Build regex pattern
    flags = re.IGNORECASE if case_insensitive else 0
    if fuzzy:
        pattern = '|'.join([fr'\b{re.escape(k)}\b' for k in keywords])
    else:
        pattern = '|'.join([re.escape(k) for k in keywords])

    # Combine LABEL/abbreviation/description fields if they exist
    text_cols = [c for c in ['LABEL', 'abbreviation', 'CATEGORY', 'param_type', 'fluid', 'specimen'] if c in df.columns]
    df['search_text'] = df[text_cols].astype(str).agg(' '.join, axis=1)

    # Search
    mask = df['search_text'].str.contains(pattern, flags=flags, regex=True)
    matches = df[mask].copy()

    # Keep key columns
    keep_cols = [c for c in ['ITEMID','LABEL','abbreviation','CATEGORY','fluid','specimen'] if c in matches.columns]
    matches = matches[keep_cols].drop_duplicates(subset=['ITEMID'])

    # Sort alphabetically for readability
    return matches.sort_values('LABEL').reset_index(drop=True)

# Time bin data helper functions

# loads in the temporal data sets
# def load_temporal_table(filename, usecols, time_col, value_col, item_col=None, ITEMIDs=None):
def load_temporal_table(df, time_col, value_col, item_col=None, ITEMIDs=None):
    """
    Takes a pre-loaded df and prepares a temporal table (like CHARTEVENTS or LABEVENTS).
    Optionally maps ITEMIDs to meaningful LABELs.
    """
    # path = f"{datapath}/{filename}"
    # df = pd.read_csv(path, usecols=usecols, low_memory=False)
    # df.columns = df.columns.str.strip().str.upper()

     # Filter by HADM_ID
    df = df[df['HADM_ID'].isin(set(map(str, training_id)))]

    # print("rows after HADM filter:", len(df))
    # print("unique ITEMIDs (sample):", df[item_col].unique()[:10])
    # print("ITEMIDs passed in (sample):", list(ITEMIDs)[:10])
    # print("types:", df[item_col].dtype, type(list(ITEMIDs)[0]))

    # Filter by ITEMIDs if provided
    if ITEMIDs is not None:
        # ITEMIDs might be a pandas Series or list; ensure it's a list
        ITEMID_list = list(ITEMIDs)
        df = df[df[item_col].isin(set(map(str, ITEMID_list)))]

    print("df ITEMID sample:", df[item_col].head(20).tolist())
    print("passed ITEMIDs sample:", ITEMID_list[:20])
    print("df unique ITEMIDs sample:", df[item_col].dropna().unique()[:20])

    # Convert to datetime
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
    df = df.dropna(subset=[time_col, value_col])

    return df


# can split to 3 timebins, find mean, max, min, and change between time bins
# will output NaN value does not exist
def bin_and_average(df, time_col, value_col, hadm_col='HADM_ID', ref_time_col=None, AGG_FUN=('mean','max'), prefix=None, add_trend=True):
    """
    Aggregates a temporal dataframe into N_BINS × BIN_HOURS windows before ref_time_col.
    Returns per-HADM_ID averaged values per bin.
    """
    results = []
    name_prefix = prefix if prefix else value_col

    # Pre-build output column names
    feature_cols = [hadm_col]
    for fun in AGG_FUN:
        for b in range(N_BINS):
            feature_cols.append(f'{name_prefix}_bin{b+1}_{fun}')
        if add_trend and fun == 'mean':
            for b in range(1, N_BINS):
                feature_cols.append(f'change_{name_prefix}_bin{b+1}_{fun}')

    # Empty or invalid DataFrame case
    if df is None or df.empty or not all(c in df.columns for c in [hadm_col, time_col, value_col]):
        print(f"⚠️ No valid data for {name_prefix}, returning NaN-filled feature table.")
        return pd.DataFrame(columns=feature_cols)

    # If ref_time_col not given, use last available time as reference
    if ref_time_col is None:
        df['REF_TIME'] = df.groupby(hadm_col)[time_col].transform('max')
        ref_time_col = 'REF_TIME'

    for hadm, sub in df.groupby(hadm_col):

        # Skip if subset empty or invalid
        if sub.empty or sub[value_col].dropna().empty:
            continue

        ref_time = pd.to_datetime(sub[ref_time_col].iloc[0])
        if pd.isna(ref_time):
            continue

        sub[time_col] = pd.to_datetime(sub[time_col])
        sub = sub.dropna(subset=[time_col, value_col])
        if sub.empty:
            continue

        # Calculate how many hours before reference
        sub['delta_h'] = (ref_time - sub[time_col]).dt.total_seconds() / 3600
        sub = sub[(sub['delta_h'] >= 0) & (sub['delta_h'] <= N_BINS * N_HOURS)]
        if sub.empty:
            # Fill with NaNs for all bins
            row = {hadm_col: hadm}
            name_prefix = prefix if prefix else value_col
            for fun in AGG_FUN:
                for b in range(N_BINS):
                    row[f'{name_prefix}_bin{b+1}_{fun}'] = np.nan
                if add_trend and fun == 'mean':
                    for b in range(1, N_BINS):
                        row[f'change_{name_prefix}_bin{b+1}_{fun}'] = np.nan
            results.append(row)
            continue

        # Compute bin index
        sub['bin'] = np.floor(sub['delta_h'] / N_HOURS).astype(int)
        sub['bin'] = N_BINS - 1 - sub['bin']  # bin2 = most recent

        row = {hadm_col: hadm}
        name_prefix = prefix if prefix else value_col

        # Aggregate per bin
        for fun in AGG_FUN:
            bin_stats = sub.groupby('bin')[value_col].agg(fun)
            for b in range(N_BINS):
                row[f'{prefix}_bin{b+1}_{fun}'] = bin_stats.get(b, np.nan)

            # add trend only for mean
            if add_trend and fun == 'mean':
                for b in range(1, N_BINS):
                    prev = bin_stats.get(b-1, np.nan)
                    curr = bin_stats.get(b, np.nan)
                    delta = curr - prev if pd.notna(curr) and pd.notna(prev) else np.nan
                    row[f'change_{prefix}_bin{b+1}_{fun}'] = delta

        results.append(row)

    # If all groups were empty
    if not results:
        print(f"⚠️ No valid data found for {prefix or value_col}. Returning NaN-filled table.")
        return pd.DataFrame(columns=feature_cols)
    else:
      df_out = pd.DataFrame(results)
      df_out = df_out.groupby('HADM_ID').mean(numeric_only=True).reset_index()
      return df_out

# generating arrays of ids for vitals
d_items = load_filtered_csv_stream('D_ITEMS.csv', training_id, usecols=['ITEMID','LABEL'])

heart_ids = find_ITEMIDs_by_LABEL(d_items, keywords=['heart rate','atrial rate'], fuzzy=True)
# print(heart_ids)
heart_ids1 = [211,220045];
# print(heart_ids)

sbp_ids = find_ITEMIDs_by_LABEL(d_items, ['blood pressure','systolic'])
# print(sbp_ids)
sbp_ids1 = [6,225309,6701,51,220052,3313,3315,3317,3321,3323,480,482]

dbp_ids = find_ITEMIDs_by_LABEL(d_items, ['blood pressure','diastolic'])
# print(dbp_ids)
dbp_ids1 = [8364,225310,8555,8368,220051,8502,8503,8504,8505,8506,8507,8444,8445,8446]

temp_ids = find_ITEMIDs_by_LABEL(d_items, ['temperature','temp'])
# print(temp_ids)
temp_ids1 = [676,677,223762]

spo2_ids = find_ITEMIDs_by_LABEL(d_items, ['spo2','oxygen saturation'])
# print(spo2_ids)
spo2_ids1 = [228232,646,6719]

MAP_ids = find_ITEMIDs_by_LABEL(d_items, ['map','mean arterial pressure'])
# print(MAP_ids)
MAP_ids1 = [6399, 2309, 2544, 2974, 3067, 6605, 1199, 2522, 6579,438,2369,1321,2770,5804]


# FOR FUTURE - partially manually done, so may not emcompass all the applicable ITEMID's of a larger dataset... need to find a better system

# loading chart events

chartevents_df = load_filtered_csv_stream('CHARTEVENTS.csv', training_id, usecols=['HADM_ID','CHARTTIME','ITEMID','VALUENUM'])
print(chartevents_df)

chartevents_df.to_csv(f"{OUTDIR}/chartevents_df.csv", index=False)

# putting together temporal bins for vitals

heart_ids1 = [211,220045];

# PULSE
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=heart_ids1
)
print(vitals)
# (c) average across all heart-rate-type ITEMIDs per time
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
heart_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="pulse")
#save_section(heart_features, "01_pulse")

print(heart_features.head())


sbp_ids1 = [6,225309,6701,51,220052,3313,3315,3317,3321,3323,480,482]

# SYS BLOOD PRESSURE
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=sbp_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
sys_bp_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="sys_bp")

#save_section(sys_bp_features, "02_sysbp")
print(sys_bp_features.head())


dbp_ids1 = [8364,225310,8555,8368,220051,8502,8503,8504,8505,8506,8507,8444,8445,8446]

# DIAS BLOOD PRESSURE
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=dbp_ids1
)

# (c)  get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
dias_bp_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="dias_bp")

#save_section(dias_bp_features, "03_diasbp")
print(dias_bp_features.head())


# MAP
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=MAP_ids1
)

# (c)  get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
print(vitals_grouped)

# (d) bin into temporal windows
MAP_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean','min'), prefix="MAP")

#save_section(MAP_features, "04_MAP")
print(MAP_features.head())


temp_ids1 = [676,677,223762]

# TEMP
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=temp_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
temp_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="temp")

#save_section(temp_features, "05_temp")
print(temp_features.head())


spo2_ids1 = [228232,646,6719]

# SPO2
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=spo2_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
spo2_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean','min'), prefix="spo2")

#save_section(spo2_features, "06_spo2")
print(spo2_features.head())

# combining all vitals feature tables into a single one

import os, glob
from functools import reduce

# # import parquets from drive
# paths = sorted(glob.glob(f"{OUTDIR}/*.parquet"))
# dfs = [pd.read_parquet(p) for p in paths]

# # vitals_features = [heart_features, sys_bp_features, dias_bp_features, MAP_features, temp_features, spo2_features]
# vitals_features = dfs[0];
# for d in dfs[1:]:
#     vitals_features = vitals_features.merge(d, on="HADM_ID", how="left")

# vitals_feature_table = reduce(
#     lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  vitals_features)

# delete parquets after
for path in glob.glob(f"{OUTDIR}/*.parquet"):
    os.remove(path)


# WITHOUT PARQUETS
vitals_features = [heart_features, sys_bp_features, dias_bp_features, MAP_features, temp_features, spo2_features]

vitals_feature_table = reduce(
    lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  vitals_features)

# print(vitals_feature_table)
list(vitals_feature_table.columns)
vitals_feature_table.to_csv(f"{OUTDIR}/vitals_feature_table.csv", index=False)

# calculating MAP if empty, and if blood pressure is given

# vitals_feature_table1 = vitals_feature_table.copy()

# timebin 1
map_cols = [c for c in vitals_feature_table.columns if "MAP_bin1_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin1_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin1_mean" in c]

print(map_cols, sbp_cols, dbp_cols)

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):
    print(map_col, sbp_col, dbp_col)

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# time bin2

map_cols = [c for c in vitals_feature_table.columns if "MAP_bin2_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin2_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin2_mean" in c]

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# time bin 3

map_cols = [c for c in vitals_feature_table.columns if "MAP_bin3_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin3_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin3_mean" in c]

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# change in MAP

map1_cols = [c for c in vitals_feature_table.columns if "MAP_bin1_mean" in c]
map2_cols = [c for c in vitals_feature_table.columns if "MAP_bin2_mean" in c]
map3_cols = [c for c in vitals_feature_table.columns if "MAP_bin3_mean" in c]

dmap2_cols = [c for c in vitals_feature_table.columns if "change_MAP_bin2_mean" in c]
dmap3_cols = [c for c in vitals_feature_table.columns if "change_MAP_bin3_mean" in c]

for map1_col, map2_col, map3_col, dmap2_col, dmap3_col in zip(map1_cols, map2_cols, map3_cols, dmap2_cols, dmap3_cols):

    # change between time bins 1 and 2
    mask2 = vitals_feature_table[dmap2_col].isna() & \
           vitals_feature_table[map1_col].notna() & \
           vitals_feature_table[map2_col].notna()

    # change between time bins 2 and 3
    mask3 = vitals_feature_table[dmap3_col].isna() & \
           vitals_feature_table[map2_col].notna() & \
           vitals_feature_table[map3_col].notna()

    vitals_feature_table.loc[mask2, dmap2_col] = (
        vitals_feature_table.loc[mask, map2_col] -
        vitals_feature_table.loc[mask, map1_col])

    vitals_feature_table.loc[mask3, dmap3_col] = (
        vitals_feature_table.loc[mask, map3_col] -
        vitals_feature_table.loc[mask, map2_col])


# print(vitals_feature_table['MAP_bin1_mean'])
list(vitals_feature_table.columns)
vitals_feature_table.to_csv(f"{OUTDIR}/vitals_feature_table.csv", index=False)

# finding ITEMIDs for lab

d_lab = load_filtered_csv_stream('D_LABITEMS.csv', training_id, usecols=['ITEMID','LABEL','FLUID','CATEGORY'])

# CREATININE - urine
lab_keywords = ['creatinine']
creatinine_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(creatinine_ids)
creatinine_ids1 = [51067,51080,51081,51006]

# WBC - urine + blood
lab_keywords = ['wbc','white blood']
wbc_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(wbc_ids)
wbc_urine_ids1 = [51516,51517,51518]
wbc_blood_ids1 = [51300]

# LACTATE
lab_keywords = ['lactate']
lactate_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(lactate_ids)
lactate_ids1 = [50813]

# BUN - blood urea nitrogran
lab_keywords = ['nitrogen','urea','bun']
BUN_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(BUN_ids)
BUN_ids1 = [51006]

# AST - aspartate aminotransferase
lab_keywords = ['aspartate','aminotransferase', 'ast']
AST_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(AST_ids)
AST_ids1 = [50878]

# ALT - alanine aminotransferase
ALT_ids1 = [50861]

# BILIRUBIN - urine + blood direct / total
lab_keywords = ['bilirubin']
bilirubin_urine_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(bilirubin_ids)
bilirubin_urine_ids1 = [51464,51465]
bilirubin_dir_ids1 = [50883]
bilirubin_tot_ids1 = [50885]

# GLUCOSE - urine + blood
lab_keywords = ['glucose']
gluc_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(gluc_ids)
gluc_blood_ids1 = [50809,50931,51529]
gluc_urine_ids1 = [51478,51084]

# Na - blood + urine
lab_keywords = ['na','sodium']
Na_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(Na_ids)
Na_blood_ids1 = [50983,50824]
Na_urine_ids1 = [51100]

# K - blood + urine
lab_keywords = ['k','potassium']
pott_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(pott_ids)
pott_blood_ids1 = [50971,50822]
pott_urine_ids1 = [51097]

# BICARBONATE - blood + urine
lab_keywords = ['bicarbonate','bicarb']
bicarb_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(bicarb_ids)
bicarb_blood_ids1 = [50882,50803]
bicarb_urine_ids1 = [51076]

# HEMOGLOBIN
lab_keywords = ['hemoglobin']
hemoglob_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(hemoglob_ids)
hemoglob_ids1 = [50811,51222]

# PLATELETS
lab_keywords = ['platelets']
platelets_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(platelets_ids)
platelets_ids1 = [51240]

# blood pH
lab_keywords = ['pH']
blood_pH_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
# print(blood_pH_ids)
blood_pH_ids1 = [50820]

# blood CO2
lab_keywords = ['pCO2']
blood_pCO2_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(blood_pCO2_ids)
blood_pCO2_ids1 = [50818]

# blood O2
lab_keywords = ['pO2']
blood_pO2_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(blood_pO2_ids)
blood_pO2_ids1 = [50821]

# loading lab events

labevents_df = load_filtered_csv_stream('LABEVENTS.csv', training_id, usecols=['HADM_ID','ITEMID','CHARTTIME','VALUENUM'])
print(chartevents_df)

labevents_df.to_csv(f"{OUTDIR}/labevents_df.csv", index=False)

# turning lab stuff into temporal bins

# WBC urine
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=wbc_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
WBC_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="WBC_urine",)
print(WBC_urine_features.head())

# WBC blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=wbc_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
WBC_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="WBC_blood",)
print(WBC_blood_features.head())

# Lactate
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=lactate_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
lactate_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="lactate",)
print(lactate_features.head())

# Creatinine
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=creatinine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
creatinine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="creatinine",)
print(creatinine_features.head())

# BUN
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=BUN_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
BUN_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="BUN",)
print(BUN_features.head())

# AST
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=AST_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
AST_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="AST",)
print(AST_features.head())

# ALT
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=ALT_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
ALT_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="ALT",)
print(ALT_features.head())

# BILIRUBIN - urine / dir / tot
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bilirubin_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bili_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bili_urine",)
print(bili_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bilirubin_dir_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bili_dir_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bili_dir",)
print(bili_dir_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bilirubin_tot_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bili_tot_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bili_tot",)
print(bili_tot_features.head())

# GLUCOSE - urine / blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=gluc_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
gluc_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="gluc_urine",)
print(gluc_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=gluc_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
gluc_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="gluc_blood",)
print(gluc_blood_features.head())

# Na - urine / blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=Na_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
Na_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="Na_urine",)
print(Na_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=Na_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
Na_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="Na_blood",)
print(Na_blood_features.head())

# K - urine / blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=pott_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
pott_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="pott_urine",)
print(pott_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=pott_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
pott_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="pott_blood",)
print(pott_blood_features.head())

# BICARBONATE - urine/blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bicarb_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bicarb_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bicarb_urine",)
print(bicarb_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bicarb_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bicarb_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bicarb_blood",)
print(bicarb_blood_features.head())

# HEMOGLOBIN
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=hemoglob_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
hemoglob_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="hemoglob",)
print(hemoglob_features.head())

# PLATELETS
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=platelets_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
platelets_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="platelets",)
print(platelets_features.head())

# pH, pCO2, pO2
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=blood_pH_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
blood_pH_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="blood_pH",)
print(blood_pH_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=blood_pCO2_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
blood_pCO2_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="blood_pCO2",)
print(blood_pCO2_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=blood_pO2_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
blood_pO2_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="blood_pO2",)
print(blood_pO2_features.head())

# combining the lab stuff into 1 feature table

labs_features = [WBC_urine_features,WBC_blood_features,lactate_features,creatinine_features,BUN_features,
                 AST_features,ALT_features,bili_urine_features,bili_dir_features,bili_tot_features,
                 gluc_urine_features,gluc_blood_features,Na_urine_features,Na_blood_features,pott_urine_features,
                 pott_blood_features,bicarb_urine_features,bicarb_blood_features,hemoglob_features,
                 platelets_features,blood_pH_features,blood_pCO2_features,blood_pO2_features,]

labs_feature_table = reduce(
    lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  labs_features)

print(labs_feature_table)
labs_feature_table.to_csv(f"{OUTDIR}/labs_feature_table.csv", index=False)

# Microbiology IDs
# ~~ no need to do bins ~~

micro = pd.read_csv(
    f"{datapath}/MICROBIOLOGYEVENTS.csv",
    usecols=['HADM_ID','SPEC_TYPE_DESC','ORG_NAME','AB_NAME','INTERPRETATION',],low_memory=False
)
micro = micro[micro['HADM_ID'].isin(training_id)]
micro['INTERPRETATION'] = micro['INTERPRETATION'].str.strip().str.upper()

# Keep valid INTERPRETATIONs (S, I, R) / removing NULLS
micro = micro[micro['INTERPRETATION'].isin(['S', 'I', 'R'])]

# Flag resistant (R) and intermediate (I)
micro['IS_RESISTANT'] = (micro['INTERPRETATION'] == 'R').astype(int)
micro['IS_INTERMEDIATE'] = (micro['INTERPRETATION'] == 'I').astype(int)

# If microorganisms found
culture_presence = (
    micro.groupby('HADM_ID')['ORG_NAME'].nunique().reset_index(name='NUM_ORGANISMS')
)
culture_presence['ANY_POS_CULTURE'] = (culture_presence['NUM_ORGANISMS'] > 0).astype(int)

# Proportion of resistant antibiotics among all tested
resistance_summary = (
    micro.groupby('HADM_ID')['IS_RESISTANT'].mean().reset_index(name='PROP_RESIST')
)

# Count of total antibiotics tested
num_tests = (
    micro.groupby('HADM_ID')['INTERPRETATION'].count().reset_index(name='NUM_ANTIBIOTICS')
)

# Mean proportion of intermediate results
intermediate_summary = (
    micro.groupby('HADM_ID')['IS_INTERMEDIATE'].mean().reset_index(name='PROP_INTERMED')
)

# creating feature table
micro_features_table = (
    culture_presence
    .merge(resistance_summary, on='HADM_ID', how='outer')
    .merge(intermediate_summary, on='HADM_ID', how='outer')
    .merge(num_tests, on='HADM_ID', how='outer')
)

# fill NaNs for patients with no microbiology data
micro_features_table[['NUM_ORGANISMS','ANY_POS_CULTURE','PROP_RESIST','PROP_INTERMED','NUM_ANTIBIOTICS']] = \
    micro_features_table[['NUM_ORGANISMS','ANY_POS_CULTURE','PROP_RESIST','PROP_INTERMED','NUM_ANTIBIOTICS']].fillna(0)

print(micro_features_table)

# helper function for finding overall across 3 time bins

import numpy as np
import pandas as pd

def summarize_over_window(
    df, ref_times,
    hadm_col='HADM_ID', time_col='CHARTTIME', value_col='VALUENUM',
    BIN_HOURS=N_HOURS, N_BIN=N_BINS, AGG_FUN=('mean', 'max'),
    prefix='NONE', fill_missing=True,
    ref_time_col='REF_TIME',  # <-- add this
    debug=True
):

    print(f"hi df rows: {len(df):,}  ref_times rows: {len(ref_times):,}")


    # Normalize column names
    df.columns = df.columns.str.strip().str.upper()
    ref_times.columns = ref_times.columns.str.strip().str.upper()
    hadm_col = hadm_col.upper()
    time_col = time_col.upper()
    value_col = value_col.upper()
    ref_time_col = ref_time_col.upper()

    # Safety checks
    for col in [hadm_col, time_col, value_col]:
        if col not in df.columns:
            raise KeyError(f"Column '{col}' not found in df. Columns: {df.columns.tolist()}")
    for col in [hadm_col, ref_time_col]:
        if col not in ref_times.columns:
            raise KeyError(f"Column '{col}' not found in ref_times. Columns: {ref_times.columns.tolist()}")

    # --- IMPORTANT: align join-key dtype ---
    df[hadm_col] = df[hadm_col].astype("string").str.strip()
    ref_times[hadm_col] = ref_times[hadm_col].astype("string").str.strip()

    # Ensure datetimes
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
    ref_times[ref_time_col] = pd.to_datetime(ref_times[ref_time_col], errors='coerce')

    # Optional: numeric values
    df[value_col] = pd.to_numeric(df[value_col], errors="coerce")

    if debug:
        print(f"[debug] df rows: {len(df):,}  ref_times rows: {len(ref_times):,}")
        print(f"[debug] unique hadm in df: {df[hadm_col].nunique():,}  in ref_times: {ref_times[hadm_col].nunique():,}")
        print(f"[debug] df NaT% {time_col}: {df[time_col].isna().mean():.3f}  ref NaT% {ref_time_col}: {ref_times[ref_time_col].isna().mean():.3f}")
        print(f"[debug] df NaN% {value_col}: {df[value_col].isna().mean():.3f}")

        overlap = set(df[hadm_col].dropna().unique()) & set(ref_times[hadm_col].dropna().unique())
        print(f"[debug] hadm overlap count: {len(overlap):,}")

    # Merge reference times (right keeps all ref_times hadm_ids)
    merged = df.merge(ref_times[[hadm_col, ref_time_col]], on=hadm_col, how='right')

    if debug:
        print(f"[debug] merged rows: {len(merged):,}")
        print(f"[debug] merged NaT% {time_col}: {merged[time_col].isna().mean():.3f}")
        print(f"[debug] merged NaT% {ref_time_col}: {merged[ref_time_col].isna().mean():.3f}")

    # Drop rows with missing timestamps/value before computing delta
    merged = merged.dropna(subset=[ref_time_col, time_col, value_col])

    if debug:
        print(f"[debug] after dropna timestamps+value: {len(merged):,}")

    # Calculate time difference in hours
    merged['delta'] = (merged[ref_time_col] - merged[time_col]).dt.total_seconds() / 3600.0

    # Filter valid time window
    window_hours = BIN_HOURS * N_BIN
    merged = merged[(merged['delta'] >= 0) & (merged['delta'] <= window_hours)]

    if debug:
        print(f"[debug] after window filter (0..{window_hours}h): {len(merged):,}")

    if merged.empty:
        if debug:
            print("⚠️ No matching rows found after window filter.")
        out = ref_times[[hadm_col]].copy()
        for fun in AGG_FUN:
            out[f'{prefix}_{fun}'] = np.nan if not fill_missing else 0
        return out

    # Group and aggregate
    grouped = merged.groupby(hadm_col)[value_col].agg(AGG_FUN).reset_index()
    grouped.columns = [hadm_col] + [f"{prefix}_{f}" for f in AGG_FUN]

    # Include all HADM_IDs (even those without data)
    if fill_missing:
        grouped = ref_times[[hadm_col]].merge(grouped, on=hadm_col, how='left').fillna(0)

    return grouped

# getting inputevent ITEMIDs that correspond to fluid intake

d_items = pd.read_csv(f"{datapath}/D_ITEMS.csv", low_memory=False)
d_items.columns = d_items.columns.str.strip().str.upper()

# Filter for fluids in inputevents tables
fluids = d_items[
    ((d_items['CATEGORY'] == 'Fluids/Intake') | (d_items['CATEGORY'] == 'Fluids - Other (Not In Use)')) &
    (d_items['LINKSTO'].str.contains('inputevents', case=False, na=False))
].copy()

# Sort and clean
fluids_ids = fluids[['ITEMID', 'LABEL', 'CATEGORY', 'LINKSTO']].sort_values('LABEL')
print(fluids_ids)

# # Making input tables across all time bins

# loading both INPUTEVENTS_MV and INPUTEVENTS_CV - just looking at IV fluid inputs

cols_mv = ['HADM_ID', 'ENDTIME', 'ITEMID', 'AMOUNT', 'AMOUNTUOM']
input_mv = load_filtered_csv_stream('INPUTEVENTS_MV.csv', training_id, usecols=cols_mv)
  # ENDTIME will be used as CHARTTIME
if 'ENDTIME' in input_mv.columns:
    input_mv.rename(columns={'ENDTIME': 'CHARTTIME'}, inplace=True)
print(input_mv)

cols_cv = ['HADM_ID', 'CHARTTIME', 'ITEMID', 'AMOUNT', 'AMOUNTUOM']
input_cv = load_filtered_csv_stream('INPUTEVENTS_CV.csv', training_id, usecols=cols_cv)

print(input_cv)


# # Normalize column names
# input_mv.columns = input_mv.columns.str.strip().str.upper()
# input_cv.columns = input_cv.columns.str.strip().str.upper()

# # # Ensure consistent dtypes
# for df in [input_mv, input_cv]:
#     df['HADM_ID'] = pd.to_numeric(df['HADM_ID'], errors='coerce')
#     df['AMOUNT'] = pd.to_numeric(df['AMOUNT'], errors='coerce')
# #    df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'], errors='coerce')
# #    df.dropna(subset=['HADM_ID', 'CHARTTIME', 'AMOUNT'], inplace=True)
#     df['HADM_ID'] = df['HADM_ID'].astype(int)

# # Combine them
# input_combined = pd.concat([input_mv, input_cv], axis=0, ignore_index=True)
# input_combined_training = input_combined[input_combined['HADM_ID'].isin(training_id)]
# #print(input_combined_training)


#print(fluids_ids)
# input_combined_training = input_combined_training[input_combined_training['ITEMID'].isin(fluids_ids['ITEMID'])]
#print(input_combined_training)

# #print(ref_times)

# input_combined_training.columns = input_combined_training.columns.str.strip().str.upper()
# input_mv = load_filtered_csv_stream('INPUTEVENTS_MV.csv', training_id, usecols=cols_mv)
# ()
# ref_times.columns = ref_times.columns.str.strip().str.upper()
# ref_times['HADM_ID'] = pd.to_numeric(ref_times['HADM_ID'], errors='coerce').astype('Int64')

print(f"hiii df rows: {input_combined_training.size:,}")
print(input_combined_training)
# Extract overall timebins feature
input_features_table = summarize_over_window(
    df=input_cv,
    ref_times=ref_times,
    hadm_col='HADM_ID',
    time_col='CHARTTIME',
    value_col='AMOUNT',
    BIN_HOURS=N_HOURS,       # each bin = 2 hr
    N_BIN=N_BINS,          # 3 bins = total 6 hr window
    AGG_FUN=('sum',), # total fluid input volume
    prefix='input',
    fill_missing=True
)
print(input_features_table)
input_features_table.to_csv(f"{OUTDIR}/input_features_table.csv", index=False)

# Finding output ids for

# OUTPUT
output_keywords = ['urine out']
outputs_ids = find_ITEMIDs_by_LABEL(d_items, output_keywords, fuzzy=True)
print(outputs_ids)
# lactate_ids1 = [50813]

# loading output values

# outputs = load_temporal_table(
#     filename='OUTPUTEVENTS.csv',
#     usecols=['HADM_ID','CHARTTIME','ITEMID','valueuom'],
#     time_col='CHARTTIME',
#     value_col='VALUE',
#     item_col='ITEMID',
#     ITEMIDs=outputs_ids
# )

# need to find sum across time bin
cols_out = ['HADM_ID', 'ITEMID', 'CHARTTIME', 'VALUE']
outputs = load_filtered_csv_stream('OUTPUTEVENTS.csv', training_id, usecols=cols_out)
# pd.read_csv(
#     f"{datapath}/OUTPUTEVENTS.csv", usecols=cols_out,low_memory=False)

outputs_features_table = summarize_over_window(
    df=outputs,
    ref_times=ref_times,
    hadm_col='HADM_ID',
    time_col='CHARTTIME',
    value_col='VALUE',
    BIN_HOURS=N_HOURS,       # each bin = 2 hr
    N_BIN=N_BINS,          # 3 bins = total 6 hr window
    AGG_FUN=('sum',), # total fluid input volume
    prefix='outputs',
    fill_missing=True
)
print(outputs_features_table)
outputs_features_table.to_csv(f"{OUTDIR}/outputs_features_table.csv", index=False)

# COMBINING ALL INTO SINGLE

static_features_table_encoded['HADM_ID'] = pd.to_numeric(static_features_table_encoded['HADM_ID'], errors='coerce').astype('Int64')
vitals_feature_table['HADM_ID'] = pd.to_numeric(vitals_feature_table['HADM_ID'], errors='coerce').astype('Int64')
labs_feature_table['HADM_ID'] = pd.to_numeric(labs_feature_table['HADM_ID'], errors='coerce').astype('Int64')
micro_features_table['HADM_ID'] = pd.to_numeric(micro_features_table['HADM_ID'], errors='coerce').astype('Int64')
input_features_table['HADM_ID'] = pd.to_numeric(input_features_table['HADM_ID'], errors='coerce').astype('Int64')
outputs_features_table['HADM_ID'] = pd.to_numeric(outputs_features_table['HADM_ID'], errors='coerce').astype('Int64')


all_features = [static_features_table_encoded, vitals_feature_table, labs_feature_table, micro_features_table, input_features_table, outputs_features_table]

all_features_table = reduce(
    lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  all_features)

#print(all_features_table)
all_features_table.head()

all_features_table.to_csv(f"{datapath}/all_features_table.csv", index=False)

"""# Testing Neural Network"""

!git clone https://github.com/scikit-learn/scikit-learn.git

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score

# defining features and LABELs

df = df_encoded.copy()

y = df["sepsis_LABEL"]
X = df.drop(columns=["sepsis_LABEL"])

X = X.apply(pd.to_numeric, errors='coerce').fillna(0)

# splitting up training vs. testing data

# X = feature matrix (numpy or pandas), y = LABELs
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# recommended settings for medical dataset
mlp = MLPClassifier(
    hidden_layer_sizes=(128, 64, 32),
    activation='relu',
    solver='adam',
    alpha=1e-4,              # L2 regularization
    learning_rate='adaptive',
    max_iter=1000,
    early_stopping=True,     # avoid overfitting
    n_iter_no_change=20,
    random_state=42
)

# Train
mlp.fit(X_train_scaled, y_train)

# Evaluation
y_pred = mlp.predict(X_test_scaled)
y_prob = mlp.predict_proba(X_test_scaled)[:, 1]

print("AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))

# visualization of performance

import matplotlib.pyplot as plt

plt.plot(mlp.loss_curve_)
plt.title("MLP Training Loss")
plt.xLABEL("Iteration")
plt.yLABEL("Loss")
plt.grid()
plt.show()

# easy way to save model for GUI to run

# import joblib

# joblib.dump(mlp, "sepsis_mlp_model.pkl")
# joblib.dump(scaler, "sepsis_mlp_scaler.pkl")

"""# Testing Decision Tree

"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report

df = df_encoded.copy()

y = df["sepsis_LABEL"]
X = df.drop(columns=["sepsis_LABEL"])

# ensure numeric
X = X.apply(pd.to_numeric, errors='coerce').fillna(0)

# splitting up training vs. testing data

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

dt = DecisionTreeClassifier(
    criterion='gini',        # or 'entropy'
    max_depth=10,            # prevent overfitting
    min_samples_split=20,
    min_samples_leaf=10,
    class_weight='balanced', # important for sepsis
    random_state=42
)

# training

dt.fit(X_train, y_train)

# evaluation of performance

y_pred = dt.predict(X_test)
y_prob = dt.predict_proba(X_test)[:, 1]

print("Decision Tree AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))

# visualization

from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 10))
tree.plot_tree(dt, feature_names=X.columns, filled=True, max_depth=3)
plt.show()

# saving for easy import

# import joblib
# joblib.dump(dt, "sepsis_decision_tree.pkl")

"""# Testing Random Forest

"""

df = df_encoded.copy()

y = df["sepsis_LABEL"]
X = df.drop(columns=["sepsis_LABEL"])

# Force numeric + fill missing
X = X.apply(pd.to_numeric, errors='coerce').fillna(0)

# splitting data into training and testing

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf = RandomForestClassifier(
    n_estimators=200,         # number of trees
    max_depth=None,           # allow deep trees (can tune later)
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',  # IMPORTANT for sepsis!
    n_jobs=-1,                # use all CPU cores
    random_state=42
)

rf.fit(X_train, y_train)

# performance evaluation

y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

print("Random Forest AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))


# visualization
import numpy as np

importances = rf.feature_importances_
indices = np.argsort(importances)[::-1]

for idx in indices[:20]:
    print(X.columns[idx], ":", importances[idx])

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.bar(range(20), importances[indices[:20]])
plt.xticks(range(20), X.columns[indices[:20]], rotation=90)
plt.title("Top 20 Feature Importances")
plt.show()

# saving

# import joblib
# joblib.dump(rf, "sepsis_random_forest.pkl")

"""# GC's NN training

In this Section, GC is using Pytorch to try different neural networks that could be part of the project
"""

