# -*- coding: utf-8 -*-
"""SeniorProject499.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MK2imPPqFCh4u5qFrNzZ26Qt8MiILYy

# Setting up data and paths
"""

# connecting to the drive

from google.colab import drive
drive.mount('/content/drive')

# adding path to CSVs

import csv
import pandas as pd
import numpy as np
from datetime import timedelta
import os

!ls '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files'

datapath = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files/';

# PARAMETERS
# ---------------------------

N_HOURS = 5          # length of each bin (hours)
N_BINS = 3           # number of temporal bins
AGG_FUN = 'mean'                # aggregation per bin

# create vectors to store hadm-id's we want to use for training

def remove_duplicates(arr):
    """Remove duplicate values from an array while preserving order."""
    seen = set()
    unique = []
    for x in arr:
        if x not in seen:
            unique.append(x)
            seen.add(x)
    return unique


# get list of hadmids from list of subject ids Rachael provided
path = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/train1_small_subject_ids.csv'
subject_ids = pd.read_csv(path).iloc[:, 0].tolist()
#print(subject_ids)

path = f"{datapath}/{'ADMISSIONS.csv'}"
admissions = pd.read_csv(path);
#print(admissions)
trainingset_1 = ( admissions.loc[admissions["SUBJECT_ID"].astype(int).isin(subject_ids), "HADM_ID"]
    .unique())
training_id = trainingset_1.tolist()

# training_id = set(training_set.astype("Int64").astype(str))
# print(training_set)
print(len(training_id))
print(len(subject_ids))

trainingset_1.tofile(f"{datapath}/processed CSVs/trainingset_1.csv")

# Demo list of training_ids

# Creating more sets of hadm-id's

import numpy as np
import pandas as pd

ADMISSIONS_PATH = f"{datapath}/ADMISSIONS.csv"
# trainingset_1 = pd.read_csv()

# trainingset1 = [...]  # your existing list/series of HADM_IDs
trainingset1_set = set(pd.Series(trainingset_1, dtype="string").str.strip().dropna().tolist())

# ---- Stream ADMISSIONS.csv in chunks and collect HADM_IDs not in trainingset1 ----
remaining_ids = []

chunksize = 500_000  # adjust if needed

for chunk in pd.read_csv(
    ADMISSIONS_PATH,
    usecols=["HADM_ID"],
    dtype={"HADM_ID": "string"},
    chunksize=chunksize
):
    chunk["HADM_ID"] = chunk["HADM_ID"].str.strip()
    # keep only ids not in trainingset1
    keep = chunk.loc[~chunk["HADM_ID"].isin(trainingset1_set), "HADM_ID"]
    remaining_ids.extend(keep.dropna().tolist())

# Deduplicate (ADMISSIONS should already be unique, but safe)
remaining = pd.Series(remaining_ids, dtype="string").dropna().unique()

print("Remaining unique admissions:", len(remaining))

required = 5 * 2500
assert len(remaining) >= required, f"Not enough remaining admissions (need {required})"

# ---- Sample 5 non-overlapping sets of 2500 ----
rng = np.random.default_rng(seed=42)
shuffled = rng.permutation(remaining)

groups = {}
for i in range(5):
    start = i * 2500
    end = start + 2500
    groups[f"trainingset_{i+2}"] = shuffled[start:end]

print({k: len(v) for k, v in groups.items()})

# ---- Optional: verify no overlaps ----
for name, ids in groups.items():
    assert len(set(ids) & trainingset1_set) == 0, f"Overlap with trainingset1 in {name}"

for i in range(5):
    for j in range(i + 1, 5):
        a = set(groups[f"trainingset_{i+2}"])
        b = set(groups[f"trainingset_{j+2}"])
        assert len(a & b) == 0, f"Overlap between trainingset_{i+2} and trainingset_{j+2}"

print("No overlaps anywhere ✅")

# ---- Save to CSV ----
for name, ids in groups.items():
    pd.DataFrame({"HADM_ID": ids}).to_csv(f"{datapath}/processed CSVs/{name}.csv", index=False)

print("Saved to /content/:", ", ".join([f"{k}.csv" for k in groups.keys()]))

# HELPER FUNCTIONS
# ---------------------------

# def load_filtered_csv(filename, usecols=None):
#     """Load CSV, keep only rows with HADM_ID in training_id."""
#     path = f"{datapath}/{filename}"

#     dtype_overrides = {
#         'SUBJECT_ID': 'string',
#         'HADM_ID': 'string',
#         'ICUSTAY_ID': 'string',
#         'ITEMID': 'string',
#         'ROW_ID': 'string',
#         'DOB': 'string'
#     }

#     df = pd.read_csv(path, usecols=usecols, dtype=dtype_overrides)
#     df.columns = df.columns.str.strip().str.upper()
#     if 'HADM_ID' in df.columns:
#         df = df[df['HADM_ID'].isin([str(x) for x in training_id])]
#     return df

# loading it in chunks for lower memory
def load_filtered_csv_stream(
    filename,
    training_id,
    usecols=None,
    chunksize=300_000
):
    """
    Stream CSV in chunks and keep only rows with HADM_ID in training_id.
    """

    path = f"{datapath}/{filename}"

    # Convert once for fast lookup
    training_id_set = set(str(x) for x in training_id)

    dtype_overrides = {
        'SUBJECT_ID': 'string',
        'HADM_ID': 'string',
        'ICUSTAY_ID': 'string',
        'ITEMID': 'string',
        'ROW_ID': 'string',
        'DOB': 'string'
    }

    filtered_chunks = []

    for chunk in pd.read_csv(
        path,
        usecols=usecols,
        dtype=dtype_overrides,
        chunksize=chunksize,
        low_memory=False
    ):
        # Normalize column names per chunk
        chunk.columns = chunk.columns.str.strip().str.upper()

        # Filter only if HADM_ID exists
        if 'HADM_ID' in chunk.columns:
            chunk = chunk[chunk['HADM_ID'].isin(training_id_set)]

        if not chunk.empty:
            filtered_chunks.append(chunk)

    if not filtered_chunks:
        return pd.DataFrame(columns=usecols)

    return pd.concat(filtered_chunks, ignore_index=True)


# put things into time bins
def aggregate_in_bins(df, time_col, value_cols, ref_time_col='REF_TIME'):
    """Bin events into N_HOURS windows relative to ref_time_col."""
    results = []

    for hadm, sub in df.groupby('HADM_ID'):
        ref_time = sub[ref_time_col].iloc[0] if ref_time_col in sub else sub[time_col].max()
        ref_time = pd.to_datetime(ref_time)
        sub[time_col] = pd.to_datetime(sub[time_col])

        # Compute time difference (hours) from reference
        sub['delta_h'] = (ref_time - sub[time_col]).dt.total_seconds() / 3600

        # Select only the last N_BINS * N_HOURS window
        sub = sub[sub['delta_h'] >= 0]
        sub = sub[sub['delta_h'] <= N_BINS * N_HOURS]

        # Bin index: 0 (oldest) to N_BINS-1 (most recent)
        sub['bin'] = (sub['delta_h'] // N_HOURS).astype(int)
        sub['bin'] = N_BINS - 1 - sub['bin']  # invert order (bin2 = most recent)

        # Aggregate by bin
        agg = sub.groupby('bin')[value_cols].agg(['mean','min','max','std'])
        agg.columns = ['_'.join([c, stat, f'bin{b}'])
                       for b in agg.index for c in value_cols for stat in ['mean','min','max','std']][:len(agg.columns)]
        agg['HADM_ID'] = hadm
        results.append(agg.reset_index(drop=True))

    if results:
        return pd.concat(results, ignore_index=True)
    else:
        return pd.DataFrame()


# function to help with saving files while running thru each section

import os, glob

OUTDIR = f"{datapath}/checkpoints"
os.makedirs(OUTDIR, exist_ok=True)

def save_section(df, name):
    path = f"{OUTDIR}/{name}.parquet"   # parquet is faster/smaller than csv
    df.to_parquet(path, index=False)
    print("saved", path)

"""# Preprocessing Structured Data - Selena

"""

# loading in csv files

training_id = pd.read_csv(f"{datapath}/processed CSVs/trainingset_5.csv").iloc[:, 0].tolist()

admissions = load_filtered_csv_stream('ADMISSIONS.csv', training_id, usecols=['SUBJECT_ID','HADM_ID','ADMITTIME','ADMISSION_TYPE','ETHNICITY'])
patients = load_filtered_csv_stream('PATIENTS.csv', training_id, usecols=['SUBJECT_ID','GENDER','DOB'])

print(admissions.columns.tolist())

# for FUTURE:  add randomized times
admissions['ADMITTIME'] = pd.to_datetime(admissions['ADMITTIME'])
patients['DOB'] = pd.to_datetime(patients['DOB'])
merged_static = admissions.merge(patients, on='SUBJECT_ID', how='left')
merged_static['ADMITTIME'] = pd.to_datetime(merged_static['ADMITTIME'], errors='coerce')
merged_static['DOB'] = pd.to_datetime(merged_static['DOB'], errors='coerce')

# Compute age in years
merged_static['AGE'] = ( merged_static["ADMITTIME"].dt.year - merged_static["DOB"].dt.year -
        ((merged_static["ADMITTIME"].dt.month < merged_static["DOB"].dt.month) |
        ((merged_static["ADMITTIME"].dt.month == merged_static["DOB"].dt.month) &
            (merged_static["ADMITTIME"].dt.day < merged_static["DOB"].dt.day)) ).astype(int)
)
#print(merged_static['AGE'])

# Cap maximum age to 90 (MIMIC policy)
# merged_static.loc[merged_static['AGE'] > 90, 'age'] = 90
# static_features_table = merged_static[['HADM_ID','GENDER','ADMISSION_TYPE','ETHNICITY']]
static_features_table = merged_static[['HADM_ID','SUBJECT_ID','AGE','GENDER','ADMISSION_TYPE','ETHNICITY']]

# Columns to encode
categorical_cols = ["GENDER", "ETHNICITY", "ADMISSION_TYPE"]

# Ensure they are hashable (strings)
for col in categorical_cols:
    static_features_table[col] = static_features_table[col].astype(str)

# One-hot encode
static_features_table_encoded = pd.get_dummies(static_features_table, columns=categorical_cols, dtype = int, drop_first=False)

print(static_features_table_encoded)
static_features_table_encoded.to_csv(f"{OUTDIR}/static_features_table.csv", index=False)

# creating reference times for each HADM_ID
# ~~ currently just time of latest entry, but will want to randomize in the future

# Ensure datetime conversion
df = load_filtered_csv_stream('CHARTEVENTS.csv', training_id, usecols=['HADM_ID','CHARTTIME'])
hadm_col='HADM_ID'
time_col='CHARTTIME'
#print(df)

df = df.copy()
df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
df = df.dropna(subset=[hadm_col, time_col])

# Group and get the latest time per admission
ref_times = (
    df.groupby(hadm_col, as_index=False)[time_col]
      .max()
      .rename(columns={time_col: 'REF_TIME'})
)

print(ref_times)
ref_times.to_csv(f"{OUTDIR}/ref_times.csv", index=False);

# finding the hadm-ids of similar items (i.e. "heart rate" and "heart rates")

import re

def find_ITEMIDs_by_LABEL(df, keywords, case_insensitive=True, fuzzy=False):
    """
    Search D_ITEMS or D_LABITEMS for ITEMIDs whose LABEL or ABBREVIATION
    matches one or more given keywords.

    Parameters
    ----------
    dictionary_path : str
        Path to D_ITEMS.csv or D_LABITEMS.csv
    keywords : list of str
        Words/phrases to search for (e.g. ['heart rate', 'pulse'])
    case_insensitive : bool
        If True, match regardless of case.
    fuzzy : bool
        If True, use substring matching with word boundaries (slower but catches variations).

    Returns
    -------
    matches : pd.DataFrame
        Subset of the dictionary with matching ITEMIDs and LABELs
    """

    # Build regex pattern
    flags = re.IGNORECASE if case_insensitive else 0
    if fuzzy:
        pattern = '|'.join([fr'\b{re.escape(k)}\b' for k in keywords])
    else:
        pattern = '|'.join([re.escape(k) for k in keywords])

    # Combine LABEL/abbreviation/description fields if they exist
    text_cols = [c for c in ['LABEL', 'abbreviation', 'CATEGORY', 'param_type', 'fluid', 'specimen','SHORT_TITLE','LONG_TITLE'] if c in df.columns]
    df['search_text'] = df[text_cols].astype(str).agg(' '.join, axis=1)

    # Search
    mask = df['search_text'].str.contains(pattern, flags=flags, regex=True)
    matches = df[mask].copy()

    # Keep key columns
    keep_cols = [c for c in ['ITEMID','LABEL','abbreviation','CATEGORY','fluid','specimen','SHORT_TITLE','LONG_TITLE'] if c in matches.columns]
    matches = matches[keep_cols].drop_duplicates(subset=['ITEMID'])

    # Sort alphabetically for readability
    return matches.sort_values('LABEL').reset_index(drop=True)

# Time bin data helper functions

# loads in the temporal data sets
# def load_temporal_table(filename, usecols, time_col, value_col, item_col=None, ITEMIDs=None):
def load_temporal_table(df, time_col, value_col, item_col=None, ITEMIDs=None):
    """
    Takes a pre-loaded df and prepares a temporal table (like CHARTEVENTS or LABEVENTS).
    Optionally maps ITEMIDs to meaningful LABELs.
    """
    # path = f"{datapath}/{filename}"
    # df = pd.read_csv(path, usecols=usecols, low_memory=False)
    # df.columns = df.columns.str.strip().str.upper()

     # Filter by HADM_ID
    df = df[df['HADM_ID'].isin(set(map(str, training_id)))]

    # print("rows after HADM filter:", len(df))
    # print("unique ITEMIDs (sample):", df[item_col].unique()[:10])
    # print("ITEMIDs passed in (sample):", list(ITEMIDs)[:10])
    # print("types:", df[item_col].dtype, type(list(ITEMIDs)[0]))

    # Filter by ITEMIDs if provided
    if ITEMIDs is not None:
        # ITEMIDs might be a pandas Series or list; ensure it's a list
        ITEMID_list = list(ITEMIDs)
        df = df[df[item_col].isin(set(map(str, ITEMID_list)))]

    print("df ITEMID sample:", df[item_col].head(20).tolist())
    print("passed ITEMIDs sample:", ITEMID_list[:20])
    print("df unique ITEMIDs sample:", df[item_col].dropna().unique()[:20])

    # Convert to datetime
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
    df = df.dropna(subset=[time_col, value_col])

    return df


# can split to 3 timebins, find mean, max, min, and change between time bins
# will output NaN value does not exist
def bin_and_average(df, time_col, value_col, hadm_col='HADM_ID', ref_time_col=None, AGG_FUN=('mean','max'), prefix=None, add_trend=True):
    """
    Aggregates a temporal dataframe into N_BINS × BIN_HOURS windows before ref_time_col.
    Returns per-HADM_ID averaged values per bin.
    """
    results = []
    name_prefix = prefix if prefix else value_col

    # Pre-build output column names
    feature_cols = [hadm_col]
    for fun in AGG_FUN:
        for b in range(N_BINS):
            feature_cols.append(f'{name_prefix}_bin{b+1}_{fun}')
        if add_trend and fun == 'mean':
            for b in range(1, N_BINS):
                feature_cols.append(f'change_{name_prefix}_bin{b+1}_{fun}')

    # Empty or invalid DataFrame case
    if df is None or df.empty or not all(c in df.columns for c in [hadm_col, time_col, value_col]):
        print(f"⚠️ No valid data for {name_prefix}, returning NaN-filled feature table.")
        return pd.DataFrame(columns=feature_cols)

    # If ref_time_col not given, use last available time as reference
    if ref_time_col is None:
        df['REF_TIME'] = df.groupby(hadm_col)[time_col].transform('max')
        ref_time_col = 'REF_TIME'

    for hadm, sub in df.groupby(hadm_col):

        # Skip if subset empty or invalid
        if sub.empty or sub[value_col].dropna().empty:
            continue

        ref_time = pd.to_datetime(sub[ref_time_col].iloc[0])
        if pd.isna(ref_time):
            continue

        sub[time_col] = pd.to_datetime(sub[time_col])
        sub = sub.dropna(subset=[time_col, value_col])
        if sub.empty:
            continue

        # Calculate how many hours before reference
        sub['delta_h'] = (ref_time - sub[time_col]).dt.total_seconds() / 3600
        sub = sub[(sub['delta_h'] >= 0) & (sub['delta_h'] <= N_BINS * N_HOURS)]
        if sub.empty:
            # Fill with NaNs for all bins
            row = {hadm_col: hadm}
            name_prefix = prefix if prefix else value_col
            for fun in AGG_FUN:
                for b in range(N_BINS):
                    row[f'{name_prefix}_bin{b+1}_{fun}'] = np.nan
                if add_trend and fun == 'mean':
                    for b in range(1, N_BINS):
                        row[f'change_{name_prefix}_bin{b+1}_{fun}'] = np.nan
            results.append(row)
            continue

        # Compute bin index
        sub['bin'] = np.floor(sub['delta_h'] / N_HOURS).astype(int)
        sub['bin'] = N_BINS - 1 - sub['bin']  # bin2 = most recent

        row = {hadm_col: hadm}
        name_prefix = prefix if prefix else value_col

        # Aggregate per bin
        for fun in AGG_FUN:
            bin_stats = sub.groupby('bin')[value_col].agg(fun)
            for b in range(N_BINS):
                row[f'{prefix}_bin{b+1}_{fun}'] = bin_stats.get(b, np.nan)

            # add trend only for mean
            if add_trend and fun == 'mean':
                for b in range(1, N_BINS):
                    prev = bin_stats.get(b-1, np.nan)
                    curr = bin_stats.get(b, np.nan)
                    delta = curr - prev if pd.notna(curr) and pd.notna(prev) else np.nan
                    row[f'change_{prefix}_bin{b+1}_{fun}'] = delta

        results.append(row)

    # If all groups were empty
    if not results:
        print(f"⚠️ No valid data found for {prefix or value_col}. Returning NaN-filled table.")
        return pd.DataFrame(columns=feature_cols)
    else:
      df_out = pd.DataFrame(results)
      df_out = df_out.groupby('HADM_ID').mean(numeric_only=True).reset_index()
      return df_out

# generating arrays of ids for vitals
d_items = load_filtered_csv_stream('D_ITEMS.csv', training_id, usecols=['ITEMID','LABEL'])

heart_ids = find_ITEMIDs_by_LABEL(d_items, keywords=['heart rate','atrial rate'], fuzzy=True)
# print(heart_ids)
heart_ids1 = [211,220045];
# print(heart_ids)

sbp_ids = find_ITEMIDs_by_LABEL(d_items, ['blood pressure','systolic'])
# print(sbp_ids)
sbp_ids1 = [6,225309,6701,51,220052,3313,3315,3317,3321,3323,480,482]

dbp_ids = find_ITEMIDs_by_LABEL(d_items, ['blood pressure','diastolic'])
# print(dbp_ids)
dbp_ids1 = [8364,225310,8555,8368,220051,8502,8503,8504,8505,8506,8507,8444,8445,8446]

temp_ids = find_ITEMIDs_by_LABEL(d_items, ['temperature','temp'])
# print(temp_ids)
temp_ids1 = [676,677,223762]

spo2_ids = find_ITEMIDs_by_LABEL(d_items, ['spo2','oxygen saturation'])
# print(spo2_ids)
spo2_ids1 = [228232,646,6719]

MAP_ids = find_ITEMIDs_by_LABEL(d_items, ['map','mean arterial pressure'])
# print(MAP_ids)
MAP_ids1 = [6399, 2309, 2544, 2974, 3067, 6605, 1199, 2522, 6579,438,2369,1321,2770,5804]


# FOR FUTURE - partially manually done, so may not emcompass all the applicable ITEMID's of a larger dataset... need to find a better system

# loading chart events

chartevents_df = load_filtered_csv_stream('CHARTEVENTS.csv', training_id, usecols=['HADM_ID','CHARTTIME','ITEMID','VALUENUM'])
print(chartevents_df)

chartevents_df.to_csv(f"{OUTDIR}/chartevents_df.csv", index=False)

# putting together temporal bins for vitals

heart_ids1 = [211,220045];

# PULSE
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=heart_ids1
)
print(vitals)
# (c) average across all heart-rate-type ITEMIDs per time
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
heart_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="pulse")
#save_section(heart_features, "01_pulse")

print(heart_features.head())


sbp_ids1 = [6,225309,6701,51,220052,3313,3315,3317,3321,3323,480,482]

# SYS BLOOD PRESSURE
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=sbp_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
sys_bp_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="sys_bp")

#save_section(sys_bp_features, "02_sysbp")
print(sys_bp_features.head())


dbp_ids1 = [8364,225310,8555,8368,220051,8502,8503,8504,8505,8506,8507,8444,8445,8446]

# DIAS BLOOD PRESSURE
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=dbp_ids1
)

# (c)  get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
dias_bp_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="dias_bp")

#save_section(dias_bp_features, "03_diasbp")
print(dias_bp_features.head())


# MAP
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=MAP_ids1
)

# (c)  get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
print(vitals_grouped)

# (d) bin into temporal windows
MAP_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean','min'), prefix="MAP")

#save_section(MAP_features, "04_MAP")
print(MAP_features.head())


temp_ids1 = [676,677,223762]

# TEMP
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=temp_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
temp_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', prefix="temp")

#save_section(temp_features, "05_temp")
print(temp_features.head())


spo2_ids1 = [228232,646,6719]

# SPO2
vitals = load_temporal_table(
    df=chartevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=spo2_ids1
)

# (c) get rid of duplicate entries
vitals_grouped = vitals.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()

# (d) bin into temporal windows
spo2_features = bin_and_average(vitals_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean','min'), prefix="spo2")

#save_section(spo2_features, "06_spo2")
print(spo2_features.head())

# combining all vitals feature tables into a single one

import os, glob
from functools import reduce

# # import parquets from drive
# paths = sorted(glob.glob(f"{OUTDIR}/*.parquet"))
# dfs = [pd.read_parquet(p) for p in paths]

# # vitals_features = [heart_features, sys_bp_features, dias_bp_features, MAP_features, temp_features, spo2_features]
# vitals_features = dfs[0];
# for d in dfs[1:]:
#     vitals_features = vitals_features.merge(d, on="HADM_ID", how="left")

# vitals_feature_table = reduce(
#     lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  vitals_features)

# delete parquets after
for path in glob.glob(f"{OUTDIR}/*.parquet"):
    os.remove(path)


# WITHOUT PARQUETS
vitals_features = [heart_features, sys_bp_features, dias_bp_features, MAP_features, temp_features, spo2_features]

vitals_feature_table = reduce(
    lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  vitals_features)

# print(vitals_feature_table)
list(vitals_feature_table.columns)
vitals_feature_table.to_csv(f"{OUTDIR}/vitals_feature_table.csv", index=False)

# calculating MAP if empty, and if blood pressure is given

# vitals_feature_table1 = vitals_feature_table.copy()

# timebin 1
map_cols = [c for c in vitals_feature_table.columns if "MAP_bin1_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin1_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin1_mean" in c]

print(map_cols, sbp_cols, dbp_cols)

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):
    print(map_col, sbp_col, dbp_col)

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# time bin2

map_cols = [c for c in vitals_feature_table.columns if "MAP_bin2_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin2_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin2_mean" in c]

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# time bin 3

map_cols = [c for c in vitals_feature_table.columns if "MAP_bin3_mean" in c]
sbp_cols = [c for c in vitals_feature_table.columns if "sys_bp_bin3_mean" in c]
dbp_cols = [c for c in vitals_feature_table.columns if "dias_bp_bin3_mean" in c]

for map_col, sbp_col, dbp_col in zip(map_cols, sbp_cols, dbp_cols):

    mask = vitals_feature_table[map_col].isna() & \
           vitals_feature_table[sbp_col].notna() & \
           vitals_feature_table[dbp_col].notna()

    vitals_feature_table.loc[mask, map_col] = (
        vitals_feature_table.loc[mask, sbp_col] +
        2 * vitals_feature_table.loc[mask, dbp_col]
    ) / 3


# change in MAP

map1_cols = [c for c in vitals_feature_table.columns if "MAP_bin1_mean" in c]
map2_cols = [c for c in vitals_feature_table.columns if "MAP_bin2_mean" in c]
map3_cols = [c for c in vitals_feature_table.columns if "MAP_bin3_mean" in c]

dmap2_cols = [c for c in vitals_feature_table.columns if "change_MAP_bin2_mean" in c]
dmap3_cols = [c for c in vitals_feature_table.columns if "change_MAP_bin3_mean" in c]

for map1_col, map2_col, map3_col, dmap2_col, dmap3_col in zip(map1_cols, map2_cols, map3_cols, dmap2_cols, dmap3_cols):

    # change between time bins 1 and 2
    mask2 = vitals_feature_table[dmap2_col].isna() & \
           vitals_feature_table[map1_col].notna() & \
           vitals_feature_table[map2_col].notna()

    # change between time bins 2 and 3
    mask3 = vitals_feature_table[dmap3_col].isna() & \
           vitals_feature_table[map2_col].notna() & \
           vitals_feature_table[map3_col].notna()

    vitals_feature_table.loc[mask2, dmap2_col] = (
        vitals_feature_table.loc[mask, map2_col] -
        vitals_feature_table.loc[mask, map1_col])

    vitals_feature_table.loc[mask3, dmap3_col] = (
        vitals_feature_table.loc[mask, map3_col] -
        vitals_feature_table.loc[mask, map2_col])


# print(vitals_feature_table['MAP_bin1_mean'])
list(vitals_feature_table.columns)
vitals_feature_table.to_csv(f"{OUTDIR}/vitals_feature_table.csv", index=False)

# finding ITEMIDs for lab

d_lab = load_filtered_csv_stream('D_LABITEMS.csv', training_id, usecols=['ITEMID','LABEL','FLUID','CATEGORY'])

# CREATININE - urine
lab_keywords = ['creatinine']
creatinine_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(creatinine_ids)
creatinine_ids1 = [51067,51080,51081,51006]

# WBC - urine + blood
lab_keywords = ['wbc','white blood']
wbc_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(wbc_ids)
wbc_urine_ids1 = [51516,51517,51518]
wbc_blood_ids1 = [51300]

# LACTATE
lab_keywords = ['lactate']
lactate_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(lactate_ids)
lactate_ids1 = [50813]

# BUN - blood urea nitrogran
lab_keywords = ['nitrogen','urea','bun']
BUN_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(BUN_ids)
BUN_ids1 = [51006]

# AST - aspartate aminotransferase
lab_keywords = ['aspartate','aminotransferase', 'ast']
AST_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(AST_ids)
AST_ids1 = [50878]

# ALT - alanine aminotransferase
ALT_ids1 = [50861]

# BILIRUBIN - urine + blood direct / total
lab_keywords = ['bilirubin']
bilirubin_urine_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(bilirubin_ids)
bilirubin_urine_ids1 = [51464,51465]
bilirubin_dir_ids1 = [50883]
bilirubin_tot_ids1 = [50885]

# GLUCOSE - urine + blood
lab_keywords = ['glucose']
gluc_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(gluc_ids)
gluc_blood_ids1 = [50809,50931,51529]
gluc_urine_ids1 = [51478,51084]

# Na - blood + urine
lab_keywords = ['na','sodium']
Na_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(Na_ids)
Na_blood_ids1 = [50983,50824]
Na_urine_ids1 = [51100]

# K - blood + urine
lab_keywords = ['k','potassium']
pott_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(pott_ids)
pott_blood_ids1 = [50971,50822]
pott_urine_ids1 = [51097]

# BICARBONATE - blood + urine
lab_keywords = ['bicarbonate','bicarb']
bicarb_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(bicarb_ids)
bicarb_blood_ids1 = [50882,50803]
bicarb_urine_ids1 = [51076]

# HEMOGLOBIN
lab_keywords = ['hemoglobin']
hemoglob_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(hemoglob_ids)
hemoglob_ids1 = [50811,51222]

# PLATELETS
lab_keywords = ['platelets']
platelets_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(platelets_ids)
platelets_ids1 = [51240]

# blood pH
lab_keywords = ['pH']
blood_pH_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
# print(blood_pH_ids)
blood_pH_ids1 = [50820]

# blood CO2
lab_keywords = ['pCO2']
blood_pCO2_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(blood_pCO2_ids)
blood_pCO2_ids1 = [50818]

# blood O2
lab_keywords = ['pO2']
blood_pO2_ids = find_ITEMIDs_by_LABEL(d_lab, lab_keywords, fuzzy=True)
#print(blood_pO2_ids)
blood_pO2_ids1 = [50821]

# loading lab events

labevents_df = load_filtered_csv_stream('LABEVENTS.csv', training_id, usecols=['HADM_ID','ITEMID','CHARTTIME','VALUENUM'])
print(chartevents_df)

labevents_df.to_csv(f"{OUTDIR}/labevents_df.csv", index=False)

# turning lab stuff into temporal bins

# WBC urine
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=wbc_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
WBC_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="WBC_urine",)
print(WBC_urine_features.head())

# WBC blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=wbc_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
WBC_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="WBC_blood",)
print(WBC_blood_features.head())

# Lactate
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=lactate_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
lactate_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="lactate",)
print(lactate_features.head())

# Creatinine
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=creatinine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
creatinine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="creatinine",)
print(creatinine_features.head())

# BUN
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=BUN_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
BUN_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="BUN",)
print(BUN_features.head())

# AST
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=AST_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
AST_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="AST",)
print(AST_features.head())

# ALT
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=ALT_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
ALT_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="ALT",)
print(ALT_features.head())

# BILIRUBIN - urine / dir / tot
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bilirubin_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bili_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bili_urine",)
print(bili_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bilirubin_dir_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bili_dir_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bili_dir",)
print(bili_dir_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bilirubin_tot_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bili_tot_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bili_tot",)
print(bili_tot_features.head())

# GLUCOSE - urine / blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=gluc_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
gluc_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="gluc_urine",)
print(gluc_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=gluc_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
gluc_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="gluc_blood",)
print(gluc_blood_features.head())

# Na - urine / blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=Na_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
Na_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="Na_urine",)
print(Na_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=Na_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
Na_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="Na_blood",)
print(Na_blood_features.head())

# K - urine / blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=pott_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
pott_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="pott_urine",)
print(pott_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=pott_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
pott_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="pott_blood",)
print(pott_blood_features.head())

# BICARBONATE - urine/blood
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bicarb_urine_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bicarb_urine_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bicarb_urine",)
print(bicarb_urine_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=bicarb_blood_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
bicarb_blood_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="bicarb_blood",)
print(bicarb_blood_features.head())

# HEMOGLOBIN
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=hemoglob_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
hemoglob_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="hemoglob",)
print(hemoglob_features.head())

# PLATELETS
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=platelets_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
platelets_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="platelets",)
print(platelets_features.head())

# pH, pCO2, pO2
labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=blood_pH_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
blood_pH_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="blood_pH",)
print(blood_pH_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=blood_pCO2_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
blood_pCO2_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="blood_pCO2",)
print(blood_pCO2_features.head())

labs = load_temporal_table(
    df=labevents_df,
    time_col='CHARTTIME',
    value_col='VALUENUM',
    item_col='ITEMID',
    ITEMIDs=blood_pO2_ids1
)
labs_grouped = labs.groupby(['HADM_ID','CHARTTIME'])['VALUENUM'].mean().reset_index()
blood_pO2_features = bin_and_average(labs_grouped, time_col='CHARTTIME', value_col='VALUENUM', AGG_FUN=('mean',), prefix="blood_pO2",)
print(blood_pO2_features.head())

# combining the lab stuff into 1 feature table

labs_features = [WBC_urine_features,WBC_blood_features,lactate_features,creatinine_features,BUN_features,
                 AST_features,ALT_features,bili_urine_features,bili_dir_features,bili_tot_features,
                 gluc_urine_features,gluc_blood_features,Na_urine_features,Na_blood_features,pott_urine_features,
                 pott_blood_features,bicarb_urine_features,bicarb_blood_features,hemoglob_features,
                 platelets_features,blood_pH_features,blood_pCO2_features,blood_pO2_features,]

labs_feature_table = reduce(
    lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  labs_features)

print(labs_feature_table)
labs_feature_table.to_csv(f"{OUTDIR}/labs_feature_table.csv", index=False)

# Microbiology IDs
# ~~ no need to do bins ~~

micro = pd.read_csv(
    f"{datapath}/MICROBIOLOGYEVENTS.csv",
    usecols=['HADM_ID','SPEC_TYPE_DESC','ORG_NAME','AB_NAME','INTERPRETATION',],low_memory=False
)
micro = micro[micro['HADM_ID'].isin(training_id)]
micro['INTERPRETATION'] = micro['INTERPRETATION'].str.strip().str.upper()

# Keep valid INTERPRETATIONs (S, I, R) / removing NULLS
micro = micro[micro['INTERPRETATION'].isin(['S', 'I', 'R'])]

# Flag resistant (R) and intermediate (I)
micro['IS_RESISTANT'] = (micro['INTERPRETATION'] == 'R').astype(int)
micro['IS_INTERMEDIATE'] = (micro['INTERPRETATION'] == 'I').astype(int)

# If microorganisms found
culture_presence = (
    micro.groupby('HADM_ID')['ORG_NAME'].nunique().reset_index(name='NUM_ORGANISMS')
)
culture_presence['ANY_POS_CULTURE'] = (culture_presence['NUM_ORGANISMS'] > 0).astype(int)

# Proportion of resistant antibiotics among all tested
resistance_summary = (
    micro.groupby('HADM_ID')['IS_RESISTANT'].mean().reset_index(name='PROP_RESIST')
)

# Count of total antibiotics tested
num_tests = (
    micro.groupby('HADM_ID')['INTERPRETATION'].count().reset_index(name='NUM_ANTIBIOTICS')
)

# Mean proportion of intermediate results
intermediate_summary = (
    micro.groupby('HADM_ID')['IS_INTERMEDIATE'].mean().reset_index(name='PROP_INTERMED')
)

# creating feature table
micro_features_table = (
    culture_presence
    .merge(resistance_summary, on='HADM_ID', how='outer')
    .merge(intermediate_summary, on='HADM_ID', how='outer')
    .merge(num_tests, on='HADM_ID', how='outer')
)

# fill NaNs for patients with no microbiology data
micro_features_table[['NUM_ORGANISMS','ANY_POS_CULTURE','PROP_RESIST','PROP_INTERMED','NUM_ANTIBIOTICS']] = \
    micro_features_table[['NUM_ORGANISMS','ANY_POS_CULTURE','PROP_RESIST','PROP_INTERMED','NUM_ANTIBIOTICS']].fillna(0)

print(micro_features_table)

# helper function for finding overall across 3 time bins

import numpy as np
import pandas as pd

def summarize_over_window(
    df, ref_times,
    hadm_col='HADM_ID', time_col='CHARTTIME', value_col='VALUENUM',
    BIN_HOURS=N_HOURS, N_BIN=N_BINS, AGG_FUN=('mean', 'max'),
    prefix='NONE', fill_missing=True,
    ref_time_col='REF_TIME',  # <-- add this
    debug=True
):

    print(f"hi df rows: {len(df):,}  ref_times rows: {len(ref_times):,}")


    # Normalize column names
    df.columns = df.columns.str.strip().str.upper()
    ref_times.columns = ref_times.columns.str.strip().str.upper()
    hadm_col = hadm_col.upper()
    time_col = time_col.upper()
    value_col = value_col.upper()
    ref_time_col = ref_time_col.upper()

    # Safety checks
    for col in [hadm_col, time_col, value_col]:
        if col not in df.columns:
            raise KeyError(f"Column '{col}' not found in df. Columns: {df.columns.tolist()}")
    for col in [hadm_col, ref_time_col]:
        if col not in ref_times.columns:
            raise KeyError(f"Column '{col}' not found in ref_times. Columns: {ref_times.columns.tolist()}")

    # --- IMPORTANT: align join-key dtype ---
    df[hadm_col] = df[hadm_col].astype("string").str.strip()
    ref_times[hadm_col] = ref_times[hadm_col].astype("string").str.strip()

    # Ensure datetimes
    df[time_col] = pd.to_datetime(df[time_col], errors='coerce')
    ref_times[ref_time_col] = pd.to_datetime(ref_times[ref_time_col], errors='coerce')

    # Optional: numeric values
    df[value_col] = pd.to_numeric(df[value_col], errors="coerce")

    if debug:
        print(f"[debug] df rows: {len(df):,}  ref_times rows: {len(ref_times):,}")
        print(f"[debug] unique hadm in df: {df[hadm_col].nunique():,}  in ref_times: {ref_times[hadm_col].nunique():,}")
        print(f"[debug] df NaT% {time_col}: {df[time_col].isna().mean():.3f}  ref NaT% {ref_time_col}: {ref_times[ref_time_col].isna().mean():.3f}")
        print(f"[debug] df NaN% {value_col}: {df[value_col].isna().mean():.3f}")

        overlap = set(df[hadm_col].dropna().unique()) & set(ref_times[hadm_col].dropna().unique())
        print(f"[debug] hadm overlap count: {len(overlap):,}")

    # Merge reference times (right keeps all ref_times hadm_ids)
    merged = df.merge(ref_times[[hadm_col, ref_time_col]], on=hadm_col, how='right')

    if debug:
        print(f"[debug] merged rows: {len(merged):,}")
        print(f"[debug] merged NaT% {time_col}: {merged[time_col].isna().mean():.3f}")
        print(f"[debug] merged NaT% {ref_time_col}: {merged[ref_time_col].isna().mean():.3f}")

    # Drop rows with missing timestamps/value before computing delta
    merged = merged.dropna(subset=[ref_time_col, time_col, value_col])

    if debug:
        print(f"[debug] after dropna timestamps+value: {len(merged):,}")

    # Calculate time difference in hours
    merged['delta'] = (merged[ref_time_col] - merged[time_col]).dt.total_seconds() / 3600.0

    # Filter valid time window
    window_hours = BIN_HOURS * N_BIN
    merged = merged[(merged['delta'] >= 0) & (merged['delta'] <= window_hours)]

    if debug:
        print(f"[debug] after window filter (0..{window_hours}h): {len(merged):,}")

    if merged.empty:
        if debug:
            print("⚠️ No matching rows found after window filter.")
        out = ref_times[[hadm_col]].copy()
        for fun in AGG_FUN:
            out[f'{prefix}_{fun}'] = np.nan if not fill_missing else 0
        return out

    # Group and aggregate
    grouped = merged.groupby(hadm_col)[value_col].agg(AGG_FUN).reset_index()
    grouped.columns = [hadm_col] + [f"{prefix}_{f}" for f in AGG_FUN]

    # Include all HADM_IDs (even those without data)
    if fill_missing:
        grouped = ref_times[[hadm_col]].merge(grouped, on=hadm_col, how='left').fillna(0)

    return grouped

# getting inputevent ITEMIDs that correspond to fluid intake

d_items = pd.read_csv(f"{datapath}/D_ITEMS.csv", low_memory=False)
d_items.columns = d_items.columns.str.strip().str.upper()

# Filter for fluids in inputevents tables
fluids = d_items[
    ((d_items['CATEGORY'] == 'Fluids/Intake') | (d_items['CATEGORY'] == 'Fluids - Other (Not In Use)')) &
    (d_items['LINKSTO'].str.contains('inputevents', case=False, na=False))
].copy()

# Sort and clean
fluids_ids = fluids[['ITEMID', 'LABEL', 'CATEGORY', 'LINKSTO']].sort_values('LABEL')
print(fluids_ids)

# # Making input tables across all time bins

# loading both INPUTEVENTS_MV and INPUTEVENTS_CV - just looking at IV fluid inputs

cols_mv = ['HADM_ID', 'ENDTIME', 'ITEMID', 'AMOUNT', 'AMOUNTUOM']
input_mv = load_filtered_csv_stream('INPUTEVENTS_MV.csv', training_id, usecols=cols_mv)
  # ENDTIME will be used as CHARTTIME
if 'ENDTIME' in input_mv.columns:
    input_mv.rename(columns={'ENDTIME': 'CHARTTIME'}, inplace=True)
print(input_mv)

cols_cv = ['HADM_ID', 'CHARTTIME', 'ITEMID', 'AMOUNT', 'AMOUNTUOM']
input_cv = load_filtered_csv_stream('INPUTEVENTS_CV.csv', training_id, usecols=cols_cv)

print(input_cv)


# # Normalize column names
# input_mv.columns = input_mv.columns.str.strip().str.upper()
# input_cv.columns = input_cv.columns.str.strip().str.upper()

# # # Ensure consistent dtypes
# for df in [input_mv, input_cv]:
#     df['HADM_ID'] = pd.to_numeric(df['HADM_ID'], errors='coerce')
#     df['AMOUNT'] = pd.to_numeric(df['AMOUNT'], errors='coerce')
# #    df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'], errors='coerce')
# #    df.dropna(subset=['HADM_ID', 'CHARTTIME', 'AMOUNT'], inplace=True)
#     df['HADM_ID'] = df['HADM_ID'].astype(int)

# # Combine them
# input_combined = pd.concat([input_mv, input_cv], axis=0, ignore_index=True)
# input_combined_training = input_combined[input_combined['HADM_ID'].isin(training_id)]
# #print(input_combined_training)


#print(fluids_ids)
# input_combined_training = input_combined_training[input_combined_training['ITEMID'].isin(fluids_ids['ITEMID'])]
#print(input_combined_training)

# #print(ref_times)

# input_combined_training.columns = input_combined_training.columns.str.strip().str.upper()
# input_mv = load_filtered_csv_stream('INPUTEVENTS_MV.csv', training_id, usecols=cols_mv)
# ()
# ref_times.columns = ref_times.columns.str.strip().str.upper()
# ref_times['HADM_ID'] = pd.to_numeric(ref_times['HADM_ID'], errors='coerce').astype('Int64')

# print(f"hiii df rows: {input_combined_training.size:,}")
# print(input_combined_training)
# Extract overall timebins feature
input_features_table = summarize_over_window(
    df=input_cv,
    ref_times=ref_times,
    hadm_col='HADM_ID',
    time_col='CHARTTIME',
    value_col='AMOUNT',
    BIN_HOURS=N_HOURS,       # each bin = 2 hr
    N_BIN=N_BINS,          # 3 bins = total 6 hr window
    AGG_FUN=('sum',), # total fluid input volume
    prefix='input',
    fill_missing=True
)
print(input_features_table)
input_features_table.to_csv(f"{OUTDIR}/input_features_table.csv", index=False)

# Finding output ids for

# OUTPUT
output_keywords = ['urine out']
outputs_ids = find_ITEMIDs_by_LABEL(d_items, output_keywords, fuzzy=True)
print(outputs_ids)
# lactate_ids1 = [50813]

# loading output values

# outputs = load_temporal_table(
#     filename='OUTPUTEVENTS.csv',
#     usecols=['HADM_ID','CHARTTIME','ITEMID','valueuom'],
#     time_col='CHARTTIME',
#     value_col='VALUE',
#     item_col='ITEMID',
#     ITEMIDs=outputs_ids
# )

# need to find sum across time bin
cols_out = ['HADM_ID', 'ITEMID', 'CHARTTIME', 'VALUE']
outputs = load_filtered_csv_stream('OUTPUTEVENTS.csv', training_id, usecols=cols_out)
# pd.read_csv(
#     f"{datapath}/OUTPUTEVENTS.csv", usecols=cols_out,low_memory=False)

outputs_features_table = summarize_over_window(
    df=outputs,
    ref_times=ref_times,
    hadm_col='HADM_ID',
    time_col='CHARTTIME',
    value_col='VALUE',
    BIN_HOURS=N_HOURS,       # each bin = 2 hr
    N_BIN=N_BINS,          # 3 bins = total 6 hr window
    AGG_FUN=('sum',), # total fluid input volume
    prefix='outputs',
    fill_missing=True
)
print(outputs_features_table)
outputs_features_table.to_csv(f"{OUTDIR}/outputs_features_table.csv", index=False)

# COMBINING ALL INTO SINGLE

static_features_table_encoded['HADM_ID'] = pd.to_numeric(static_features_table_encoded['HADM_ID'], errors='coerce').astype('Int64')
vitals_feature_table['HADM_ID'] = pd.to_numeric(vitals_feature_table['HADM_ID'], errors='coerce').astype('Int64')
labs_feature_table['HADM_ID'] = pd.to_numeric(labs_feature_table['HADM_ID'], errors='coerce').astype('Int64')
micro_features_table['HADM_ID'] = pd.to_numeric(micro_features_table['HADM_ID'], errors='coerce').astype('Int64')
input_features_table['HADM_ID'] = pd.to_numeric(input_features_table['HADM_ID'], errors='coerce').astype('Int64')
outputs_features_table['HADM_ID'] = pd.to_numeric(outputs_features_table['HADM_ID'], errors='coerce').astype('Int64')


all_features = [static_features_table_encoded, vitals_feature_table, labs_feature_table, micro_features_table, input_features_table, outputs_features_table]

all_features_table = reduce(
    lambda left, right: pd.merge(left, right, on='HADM_ID', how='outer'),  all_features)

#print(all_features_table)
all_features_table.head()

all_features_table.to_csv(f"{datapath}/all_features_table.csv", index=False)

"""#Creating Output Files"""

import pandas as pd

# --------- Configure your paths ----------
datapath = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files/';
diag_path = f"{datapath}/DIAGNOSES_ICD.csv"

# --------- Sepsis ICD-9 definitions ----------
# "Explicit sepsis" style codes (common baseline):
SEPSIS_PREFIXES = ['77181','99591','99592','67020','67022','67024'];
      # septicemia, sepsis, severe sepsis, puerperal sepsis x3

def _normalize_icd9(code: str) -> str:
    """Remove dots/spaces and keep digits/letters."""
    if pd.isna(code):
        return ""
    return str(code).replace(".", "").strip()

def _build_hadm_set(hadm_ids):
    """Ensure hadm_ids is a set of strings for fast membership tests."""
    return set(pd.Series(hadm_ids).astype("string").str.strip().tolist())

def label_sepsis_from_diagnoses_icd(
    hadm_ids,
    diag_file=diag_path,
    use_broad=False,
    chunksize=500_000,
):
    """
    Returns:
      labels: list[int] aligned to hadm_ids (1 if sepsis dx present else 0)
    """

    hadm_set = _build_hadm_set(hadm_ids)

    # Choose code set
    prefixes = SEPSIS_PREFIXES

    # We'll mark positives in a dict keyed by HADM_ID (string)
    sepsis_hadm = set()

    # Stream DIAGNOSES_ICD.csv
    for chunk in pd.read_csv(
        diag_file,
        usecols=["HADM_ID", "ICD9_CODE"],
        dtype={"HADM_ID": "string", "ICD9_CODE": "string"},
        chunksize=chunksize,
    ):
        # restrict to hadm_ids of interest
        chunk["HADM_ID"] = chunk["HADM_ID"].astype("string").str.strip()
        chunk = chunk[chunk["HADM_ID"].isin(hadm_set)]
        if chunk.empty:
            continue

        # normalize ICD9 codes
        icd = chunk["ICD9_CODE"].map(_normalize_icd9)

        # match prefixes
        is_sepsis = False
        # vectorized prefix matching
        mask = pd.Series(False, index=chunk.index)
        for p in prefixes:
            mask |= icd.str.startswith(p)

        # update positives
        sepsis_hadm.update(chunk.loc[mask, "HADM_ID"].tolist())

    # Build label vector aligned to input order
    labels = [1 if str(h).strip() in sepsis_hadm else 0 for h in hadm_ids]
    return labels

# generating output file for our training set

import pandas as pd

output_path = f"{datapath}/processed CSVs/train4_all_features_table_12hrs.csv"

df = pd.read_csv(output_path)
hadm_ids = df["HADM_ID"].tolist()
print(hadm_ids[:10])

y_explicit = label_sepsis_from_diagnoses_icd(hadm_ids, use_broad=False)
print("explicit sepsis labels:", y_explicit)

out = pd.DataFrame({
    "HADM_ID": hadm_ids,
    "SEPSIS_STATUS": y_explicit
})

out.to_csv(f"{datapath}/processed CSVs/train4_small_sepsis_labels.csv", index=False)

"""# Setting up Model

---


"""

# getting PyTorch

# !pip3 uninstall -y torchvision torchaudio torch
# !pip3 cache purge
# !pip3 install torch torchvision torchaudio

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms

# load data

import csv
import pandas as pd
import numpy as np
from datetime import timedelta
import os

!ls '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files'

datapath = '/content/drive/MyDrive/25 Fall/BME499 - Senior Capstone/499 Senior Project Group - RaGS/Code/CSV Files/';

file = 'train1_combined_latest_note_1_hadm18hrs.csv'
# file = 'train1_all_features_table_15hrs.csv'
path = f"{datapath}processed CSVs/{file}"
features = pd.read_csv(path);

# Remove the column from the main dataframe
print(features.shape)
if 'NUM_ANTIBIOTICS' in features.columns:
    features = features.drop(columns=['NUM_ANTIBIOTICS'])
    print("Column 'NUM_ANTIBIOTICS' removed successfully.")
    print(features.shape)

if 'PROP_RESIST' in features.columns:
    features = features.drop(columns=['PROP_RESIST'])
    print("Column 'PROP_RESIST' removed successfully.")
    print(features.shape)

if 'NUM_ORGANISMS' in features.columns:
    features = features.drop(columns=['NUM_ORGANISMS'])
    print("Column 'NUM_ORGANISMS' removed successfully.")
    print(features.shape)

labels = pd.read_csv(f'{datapath}/processed CSVs/set 1/train1_small_sepsis_labels.csv');
ID_COL = "HADM_ID"
LABEL_COL = "SEPSIS_STATUS"

# ----------------------------
# 2) Load + merge
# ----------------------------

# Normalize columns (robust)
features.columns = features.columns.str.strip().str.upper()
labels.columns   = labels.columns.str.strip().str.upper()
ID_COL = ID_COL.upper()
print(ID_COL)
LABEL_COL = LABEL_COL.upper()
print(LABEL_COL)

# Ensure IDs are strings for safe merge
features[ID_COL] = features[ID_COL].astype("string").str.strip()
labels[ID_COL]   = labels[ID_COL].astype("string").str.strip()
print(features.shape)

# Merge: keep only admissions that have both features + labels
data = features.merge(labels[[ID_COL, LABEL_COL]], on=ID_COL, how="inner")

print("Merged shape:", data.shape)
print("Label balance:\n", data[LABEL_COL].value_counts(dropna=False))

# ----------------------------
# 2) Helper Functions (split + preprocessing + metrics)
# ----------------------------
def stratified_train_test_split(y, test_size=0.2, seed=42):
    """Return train_idx, test_idx with stratification on binary y (0/1)."""
    y = np.asarray(y).astype(int)
    rng = np.random.default_rng(seed)

    idx0 = np.where(y == 0)[0]
    idx1 = np.where(y == 1)[0]
    rng.shuffle(idx0)
    rng.shuffle(idx1)

    n0_test = int(round(len(idx0) * test_size))
    n1_test = int(round(len(idx1) * test_size))

    test_idx = np.concatenate([idx0[:n0_test], idx1[:n1_test]])
    train_idx = np.concatenate([idx0[n0_test:], idx1[n1_test:]])

    rng.shuffle(train_idx)
    rng.shuffle(test_idx)
    return train_idx, test_idx

def impute_median_fit(X):
    """Compute per-feature median ignoring NaNs."""
    med = np.nanmedian(X, axis=0)
    # If a column is all NaN, nanmedian returns NaN -> replace with 0
    med = np.where(np.isnan(med), 0.0, med)
    return med

def impute_median_transform(X, med):
    """Fill NaNs with fitted medians."""
    X2 = X.copy()
    nan_mask = np.isnan(X2)
    if nan_mask.any():
        X2[nan_mask] = np.take(med, np.where(nan_mask)[1])
    return X2

def standardize_fit(X):
    """Compute mean/std per feature; guard std=0."""
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    std = np.where(std < 1e-12, 1.0, std)
    return mean, std

def standardize_transform(X, mean, std):
    return (X - mean) / std

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def confusion_counts(y_true, y_pred):
    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)
    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())
    return tp, tn, fp, fn

def precision_recall_f1(y_true, y_pred):
    tp, tn, fp, fn = confusion_counts(y_true, y_pred)
    prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    rec  = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1   = 2*prec*rec / (prec + rec) if (prec + rec) > 0 else 0.0
    acc  = (tp + tn) / max(tp + tn + fp + fn, 1)
    return acc, prec, rec, f1, (tp, tn, fp, fn)

def roc_auc_score_np(y_true, y_score):
    """
    AUROC via rank statistic (Mann–Whitney U). Works for binary labels.
    Returns NaN if only one class present.
    """
    y_true = np.asarray(y_true).astype(int)
    y_score = np.asarray(y_score).astype(float)

    pos = y_true == 1
    neg = y_true == 0
    n_pos = pos.sum()
    n_neg = neg.sum()
    if n_pos == 0 or n_neg == 0:
        return float("nan")

    # ranks of scores (average rank for ties)
    order = np.argsort(y_score)
    ranks = np.empty_like(order, dtype=float)
    ranks[order] = np.arange(1, len(y_score) + 1)

    # handle ties: average ranks within ties
    sorted_scores = y_score[order]
    i = 0
    while i < len(sorted_scores):
        j = i
        while j + 1 < len(sorted_scores) and sorted_scores[j + 1] == sorted_scores[i]:
            j += 1
        if j > i:
            avg_rank = ranks[order[i:j+1]].mean()
            ranks[order[i:j+1]] = avg_rank
        i = j + 1

    sum_ranks_pos = ranks[pos].sum()
    # U statistic for positives
    U = sum_ranks_pos - n_pos * (n_pos + 1) / 2
    auc = U / (n_pos * n_neg)
    return float(auc)

def average_precision_score_np(y_true, y_score):
    """
    Average Precision (area under PR curve) using the common definition:
    AP = sum_n (P_n * (R_n - R_{n-1})) over thresholds at each positive.
    Returns NaN if no positives.
    """
    y_true = np.asarray(y_true).astype(int)
    y_score = np.asarray(y_score).astype(float)

    n_pos = (y_true == 1).sum()
    if n_pos == 0:
        return float("nan")

    order = np.argsort(-y_score)  # descending
    y_sorted = y_true[order]

    tp = np.cumsum(y_sorted == 1)
    fp = np.cumsum(y_sorted == 0)

    precision = tp / np.maximum(tp + fp, 1)
    recall = tp / n_pos

    # AP: sum precision at each rank where y=1, divided by n_pos
    ap = (precision[y_sorted == 1].sum()) / n_pos
    return float(ap)

# ----------------------------
# 4) Build X, y
# ----------------------------
feature_cols = [c for c in data.columns if c not in {ID_COL, LABEL_COL}]
print(len(feature_cols))
print(len(data.columns))

# Convert features to numeric; non-numeric -> NaN
X_df = data[feature_cols].apply(pd.to_numeric, errors="coerce")
y = data[LABEL_COL].astype(int).to_numpy()

X = X_df.to_numpy(dtype=np.float32)  # may contain NaN

# ----------------------------
# 5) Split (stratified)
# ----------------------------
train_idx, test_idx = stratified_train_test_split(y, test_size=0.2, seed=42)

X_train_raw, y_train = X[train_idx], y[train_idx]
X_test_raw,  y_test  = X[test_idx],  y[test_idx]

print("Train/Test sizes:", X_train_raw.shape, X_test_raw.shape)

# ----------------------------
# 6) Impute + standardize (fit on train only)
# ----------------------------
med = impute_median_fit(X_train_raw)
X_train = impute_median_transform(X_train_raw, med)
X_test  = impute_median_transform(X_test_raw,  med)

mean, std = standardize_fit(X_train)
X_train = standardize_transform(X_train, mean, std)
print(X_train)
X_test  = standardize_transform(X_test,  mean, std)
print(X_test)

# Torch tensors
X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
X_test_t  = torch.tensor(X_test,  dtype=torch.float32)
y_test_t  = torch.tensor(y_test,  dtype=torch.float32).view(-1, 1)

import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# ----------------------------
# 7) Dataset/DataLoader
# ----------------------------
class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    def __len__(self):
        return self.X.shape[0]
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_ds = TabularDataset(X_train_t, y_train_t)
test_ds  = TabularDataset(X_test_t,  y_test_t)

train_loader = DataLoader(train_ds, batch_size=64, shuffle=True)
test_loader  = DataLoader(test_ds,  batch_size=256, shuffle=False)

"""# XG BOOSTED TREE"""

import xgboost as xgb
import numpy as np
import torch
from sklearn.metrics import classification_report, fbeta_score, precision_recall_curve, auc, roc_curve, average_precision_score
import matplotlib.pyplot as plt

# 1. Convert Tensors back to Numpy
# We use .cpu().numpy() to ensure compatibility regardless of if you are on a GPU or CPU
X_train_np = X_train_t.cpu().numpy() if torch.is_tensor(X_train_t) else X_train_t
y_train_np = y_train_t.cpu().numpy() if torch.is_tensor(y_train_t) else y_train_t
X_test_np = X_test_t.cpu().numpy() if torch.is_tensor(X_test_t) else X_test_t
y_test_np = y_test_t.cpu().numpy() if torch.is_tensor(y_test_t) else y_test_t

print(X_train_np.shape)

print(f"Data ready for XGBoost. Train shape: {X_train_np.shape}, Test shape: {X_test_np.shape}")

'''
# 2. Initialize and Train XGBoost
# We use scale_pos_weight to handle the 13.38:1 imbalance ratio
xgb_model = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=150,       # Number of boosting rounds
    learning_rate=0.05,     # Smaller step size for better generalization
    max_depth=4,            # Depth of trees (keep small to prevent overfitting)
    scale_pos_weight=13.38, # CRITICAL: Your specific imbalance ratio
    subsample=0.8,          # Use 80% of data per tree to prevent overfitting
    colsample_bytree=0.8,   # Use 80% of features per tree
    eval_metric='aucpr',    # Optimize for Area Under Precision-Recall Curve
    random_state=42
)

print("Training XGBoost model...")
xgb_model.fit(X_train_np, y_train_np)
print("Model training complete.")
'''

from imblearn.over_sampling import SMOTE

# 1. Create synthetic Sepsis cases for the TRAINING set only
# This balances the dataset so the model sees more Sepsis patterns
sm = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = sm.fit_resample(X_train_np, y_train_np)
print(X_train_resampled.shape)

print(f"Original Sepsis count: {np.sum(y_train_np)}")
print(f"Resampled Sepsis count: {np.sum(y_train_resampled)}")

# 2. Re-train XGBoost on the balanced data
# Note: We remove scale_pos_weight because the data is now balanced 1:1
xgb_balanced = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=300,        # Increased, but we'll use a lower learning rate
    learning_rate=0.02,      # Slow down learning to avoid memorizing noise
    max_depth=4,             # Keep trees shallow to prevent overfitting 970 features

    # --- NEW REGULARIZATION PARAMETERS ---
    reg_alpha=1.0,           # L1 Regularization (forces unimportant feature weights to 0)
    reg_lambda=2.0,          # L2 Regularization (prevents any one feature from dominating)
    colsample_bytree=0.3,    # Only look at 30% of features for each tree (CRITICAL for 970 features)
    subsample=0.8,           # Use 80% of rows for each tree

    eval_metric='aucpr',
    random_state=42
)

xgb_balanced.fit(X_train_resampled, y_train_resampled)

# 3. Get new probabilities
y_probs_balanced = xgb_balanced.predict_proba(X_test_np)[:, 1]
# print(y_probs_balanced)

# 3. Predict Probabilities
y_probs = xgb_balanced.predict_proba(X_test_np)[:, 1]

# Set a custom threshold for clinical sensitivity
# Lowering this increases Recall (catching more sepsis cases)
threshold = 0.14
y_preds = (y_probs >= threshold).astype(int)

# Detailed Metrics
print(f"--- Results (Decision Threshold: {threshold}) ---")
print(classification_report(y_test_np, y_preds, target_names=['No Sepsis', 'Sepsis']))

# F2-Score prioritizes Recall over Precision
f2 = fbeta_score(y_test_np, y_preds, beta=2.0)
print(f"F2-Score (Recall-focused): {f2:.4f}")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Create a temporary DataFrame for the plot
plot_df = pd.DataFrame({
    'Probability': np.squeeze(y_probs),
    'Label': np.squeeze(y_test_np)
})

# 2. Map labels to names for a cleaner legend
plot_df['Label'] = plot_df['Label'].map({0: 'No Sepsis', 1: 'Sepsis'})

# 3. Create the figure
plt.figure(figsize=(10, 6))

# 4. Plot overlapping density curves (matching the screenshot style)
sns.kdeplot(
    data=plot_df,
    x='Probability',
    hue='Label',
    fill=True,           # Fills the area under the curve
    common_norm=False,   # Normalizes each curve independently (crucial for imbalanced data)
    palette={'No Sepsis': '#1f77b4', 'Sepsis': '#ff7f0e'}, # Blue and Orange
    alpha=0.5,           # Transparency for overlapping areas
    linewidth=2
)

# 5. Add the vertical threshold line
plt.axvline(x=threshold, color='red', linestyle='--', label=f'Threshold ({threshold})')

# 6. Formatting to match the screenshot
plt.title('Distribution of Predicted Probabilities by Actual Label', fontsize=14, fontweight='bold')
plt.xlabel('Predicted Probability', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.xlim(0, 1) # Probability is always between 0 and 1
plt.legend(title='Actual Status')
plt.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Calculate precision and recall for all possible thresholds
precision, recall, thresholds = precision_recall_curve(y_test_np, y_probs)

# Find the threshold that gets us closest to 80% Recall
target_recall = 0.80
idx = np.where(recall >= target_recall)[0][-1]
clinical_threshold = thresholds[idx]

# Apply this threshold
optimized_preds = (y_probs >= clinical_threshold).astype(int)

print(f"Targeting {target_recall*100}% Recall...")
print(f"Required Threshold: {clinical_threshold:.4f}")
print("\n--- Results at Clinical Threshold ---")
print(classification_report(y_test_np, optimized_preds))

# 4. Plotting Performance Curves
fpr, tpr, _ = roc_curve(y_test_np, y_probs)
roc_auc = auc(fpr, tpr)
precision, recall, _ = precision_recall_curve(y_test_np, y_probs)
auprc = average_precision_score(y_test_np, y_probs)

plt.figure(figsize=(14, 6))

# ROC Curve
plt.subplot(1, 2, 1)
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC AUC = {roc_auc:.3f}')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate (Recall)')
plt.title('Receiver Operating Characteristic (ROC)')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)

# Precision-Recall Curve
plt.subplot(1, 2, 2)
plt.plot(recall, precision, color='teal', lw=2, label=f'AUPRC = {auprc:.3f}')
plt.xlabel('Recall (Sensitivity)')
plt.ylabel('Precision (Positive Predictive Value)')
plt.title('Precision-Recall Curve')
plt.legend(loc="upper right")
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

import pandas as pd

# Get feature names from your dataframe (adjust variable name if different)
feat_importances = pd.Series(xgb_balanced.feature_importances_, index=feature_cols)

plt.figure(figsize=(10, 6))
feat_importances.nlargest(15).plot(kind='barh', color='skyblue')
plt.title("Top 15 Predictors of Sepsis (XGBoost)")
plt.xlabel("Relative Importance")
plt.gca().invert_yaxis() # Highest importance on top
plt.show()